### ISSUE TITLE
helm-do-ag-project-root doesn't work

### ISSUE THREAD

**Issue by Poquaruse** [syohex/emacs-helm-ag#100]
Hi,

first of all thanks for providing this plug-in! Unfortunately, I'm encountering problems when trying to use helm-do-ag-project-root: it doesn't show anything even thoug helm-do-ag does work for the same inputs.

I'm using Emacs 24.4.1 on Windows 8.1 Pro x64 with the latest ag.exe installed by chocolatey. Anything I can do to help debug? (I'm totally new to Emacs btw... ;-)

Thanks and best regards!

**Comment by syohex** [comment]
Sorry late response.

Would you tell me how to reproduce this issue in detail ?

I cannot reproduce this issue now. `helm-do-ag-project-root` calls `helm-do-ag` from project root,
so I suppose if `helm-do-ag` works then `helm-do-ag-project-root` works too.

**Comment by Poquaruse** [comment]
No problem, thanks for answering!

M-x helm-do-ag-project-root RET opens a prompt. Whatever I type, nothing happens. 

M-x helm-do-ag RET opens a prompt to choose a file. If I just press Enter, the directory seems to be selected. However, upon typing, nothing happens. 

If on the other hand I choose a file instead of a folder/directory I can successfully search in that file (but not in the directory). 

Does this have something to do with Windows perhaps?

**Comment by syohex** [comment]
Please upgrade `helm-ag` version and try. I fixed `helm-do-ag` issue for the platinum searcher.
So this issue may be resolved by that fix.

**Comment by Poquaruse** [comment]
Unfortunately, it does not work with the new version...

**Comment by syohex** [comment]
Thanks for checking.

**Comment by syohex** [comment]
@Poquaruse 

FYI: [the platinum searcher](https://github.com/monochromegane/the_platinum_searcher/)(`pt`) is better than the silver searcher(`ag`) for Windows users. You can download its binary from [here](https://github.com/monochromegane/the_platinum_searcher/releases).

You need to add following configuration for using the platinum searcher(`pt`) instead of the silver searcher(`ag`)
```lisp
(setq helm-ag-base-command "pt --nocolor --nogroup")
```

**Comment by Poquaruse** [comment]
Thanks! I just gave pt a try and one thing does work, the other doesn't. ;-)

OK: helm-do-ag, then select directory does successfully search all files
Doesn't work: helm-do-ag-project-root, still doesn't return any results

**Comment by syohex** [comment]
I suppose this issue was fixed by #114.
Please update to latest version and try again.

**Comment by Poquaruse** [comment]
Great! :-) I just updated and indeed it does work! Thanks for fixing this!
