### ISSUE TITLE
[feature] helm-ag in all opened buffer

### ISSUE THREAD

**Issue by syl20bnr** [syohex/emacs-helm-ag#101]
This is a feature request for spacemacs, we have currently `SPC s`to search in a directory, `SPC p s` to search in a project. I would like to add `SPC b s` to search in all opened buffers.

**Comment by syohex** [comment]
Thanks for idea. I'll try to implement.

**Comment by syl20bnr** [comment]
Works like a charm :+1: 
Thank you !
