### ISSUE TITLE
[bug report] *helm-ag-edit* buffer cannot be closed properly 

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-helm-ag#104]
How to reproduce:

- Search with `helm-do-ag`
- `C-c C-e` to enter edit buffer.
- Switch to some other buffer.
- Now you cannot switch back or you cannot create another `*helm-ag-edit*` when pressing `C-c C-e`. It simply returns an error: `Text is read-only`.

**Comment by tuhdo** [comment]
@syohex Now there's another problem: I can no longer `C-c C-e` to edit anymore. It simply said undefined key. This is with only `helm` and `helm-ag` installed.

**Comment by ejoubaud** [comment]
I get the same issue (`Text is read only`) whenever I try to edit the search (`C-c C-e` on search results). No need to switch to some other buffer.

**Comment by ejoubaud** [comment]
Actually my problem is only with the left part of the buffer. When I try any action that would affect whole lines (like evil's `d` or `:g/pattern/d`) I'll get the `Text is read-only` error. That's annoying because removing lines is my main use-case for text result editing :(

**Comment by ejoubaud** [comment]
In case anyone's wondering, the trick to solve this is a `(setq inhibit-read-only t)`. This will disable read-only chars in the whole emacs though, not just in those files, so you may want to read about `read-only` characters and `inhibit-read-only` in https://www.gnu.org/software/emacs/manual/html_node/elisp/Special-Properties.html

**Comment by syohex** [comment]
Sorry too late reply. Please use mark delete line command(By default: it is assigned to `C-c C-d`). File name and line number is necessary for changing file and helm-ag cannot update content if they are deleted. So file name and line number are read-only.

Currently it marks only one line. I'll consider for improving it(region support, match line support etc).

**Comment by idrozd** [comment]
@syohex can you please give more details? Is it some kind of workaround one can use?

**Comment by JocelynDelalande** [comment]
> Sorry too late reply. Please use mark delete line command(By default: it is assigned to `C-c C-d`). File name and line number is necessary for changing file and helm-ag cannot update content if they are deleted. So file name and line number are read-only.
> 
> Currently it marks only one line. I'll consider for improving it(region support, match line support etc).

That is only when you want to delete lines in helm-ag edit buffer.

I am still getting the `Text is read-only.` immediatly when doing C-c C-e (then, helm-ag buffer quits). I do not have the chance to go as far as trying to edit the buffer.

**Comment by JocelynDelalande** [comment]
> In case anyone's wondering, the trick to solve this is a `(setq inhibit-read-only t)`. This will disable read-only chars in the whole emacs though, not just in those files, so you may want to read about `read-only` characters and `inhibit-read-only` in https://www.gnu.org/software/emacs/manual/html_node/elisp/Special-Properties.html

Where ?

**Comment by JocelynDelalande** [comment]
Nevermind, for me the fix was to upgrade to latest melpa stable version.

Upgrade from *./elpa/helm-ag-20170209.745* to *helm-ag-20170209.1545* dit the trick.

**Comment by jjzmajic** [comment]
This is back again for me. Unfortunately, I cannot recall the hash when it started. Inhibiting read-only is a solution that's worse than the problem. Any thoughts as to what might be causing this?

**Comment by cedarbaum** [comment]
For anyone who comes across this issue, see my comment in #331 for a possible explanation.
