### ISSUE TITLE
compilation-next-error: Marker does not point anywhere [5 times]

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-helm-ag#105]
How to reproduce:

- Search with `helm-do-ag`.
- `C-c C-e`.
- `C-x k` to kill it.
- Now search and `C-c C-e` again.
- `M-g n` or `M-g p` no longer works but shows the above error.

**Comment by syohex** [comment]
Sorry too late reply.

However I cannot reproduce this issue with Emacs 24.4 and Head.

**Comment by tuhdo** [comment]
@syohex Now there's another problem: I can no longer `C-c C-e` to edit anymore. It simply said undefined key. This is with only `helm` and `helm-ag` installed.

**Comment by syohex** [comment]
Hmm, I cannot reproduce.

![helm-ag](https://cloud.githubusercontent.com/assets/554281/7514236/c105702e-f4f6-11e4-9dcf-8cfddfc011a9.gif)

Would you tell me in more detail ?
- how to reproduce 
- minimum configuration
etc

**Comment by syohex** [comment]
Please reopen if you still have problem.
