### ISSUE TITLE
Feature request: Enable space characters to interactively narrow selection

### ISSUE THREAD

**Issue by SpamBaconEggs** [syohex/emacs-helm-ag#108]
It would be great if I could further narrow the initial ag search results in the helm buffer by just typing in a space and strings to match. The idea is that the ag search gets me all options, and then the buffer search lets me narrow things based on the file path, name, and matched line in the file.

Having the first string be the regex for ag, and the subsequent space-separated strings operate on the buffer would make searching and file navigating in large code basis really rapid.

Such a change (or optional behaviour) would make helm-ag behave more like `M-x helm-find-file` or Projectiles `M-x projectile-find-file` or `M-x helm-M-x`.

I originally posed this feature request as a question on the Emacs stackexchange site in relation to Projectile's use of helm-ag: http://emacs.stackexchange.com/questions/7964/helm-projectile-ag-how-can-i-refine-the-grep-results-further

**Comment by syohex** [comment]
@SpamBaconEggs Sorry too late reply. please try to latest version.

**Comment by SpamBaconEggs** [comment]
Brilliant! Works like a charm, thanks!

**Comment by SpamBaconEggs** [comment]
Unfortunately it doesn't work when used with Projectile, but I'll raise a feature request with that project's maintainer.

**Comment by syohex** [comment]
I have improved regexp for `helm-do-ag` which is used by `helm-projectile-ag`.
Please try to latest version.
