### ISSUE TITLE
Select candidate does not work

### ISSUE THREAD

**Issue by manuel-uberti** [syohex/emacs-helm-ag#113]
Hi,

I am using latest ```helm-ag``` from MELPA.
When I issue ```M-x helm-ag``` and type a pattern, the ```helm-ag``` buffer correctly shows the matching results.
However, when I select a candidate with ```RET``` the corresponding file is not opened.
It works fine with ```helm-do-ag```.

**Comment by syohex** [comment]
Would you tell me how to reproduce this issue and your platform information(OS, `ag` version, Emacs version etc) ?

**Comment by manuel-uberti** [comment]
Sure.

OS: ```Debian unstable```
ag: ```silversearcher-ag 0.30.0-1```
Emacs: trunk, build ```59db430```

I simply call ```helm-ag``` (I tried both with and without universal argument), write a pattern, head over the candidate and hit ```RET```.

**Comment by syohex** [comment]
Hmm, I cannot reproduce. I use latest Emacs and silver searcher and `helm-ag`.

![helm-ag](https://cloud.githubusercontent.com/assets/554281/7953428/838ef10c-09ff-11e5-84a0-da915ec5c2bc.gif)

**Comment by manuel-uberti** [comment]
Weird, well I can use ```helm-do-ag```. Consider it close, then.
