### ISSUE TITLE
Is there a way to select multiple directories to search into?

### ISSUE THREAD

**Issue by CestDiego** [syohex/emacs-helm-ag#115]
It would be cool if one could select directories with helm in helm-ag and browse among those directories, I don't know if it's supported by ag, but I think it would be a cool adition

**Comment by syohex** [comment]
@CestDiego Sorry too late reply.

I have implemented and merged multiple directories feature at #127.
You can use this feature by `C-u C-u M-x helm-ag`.

Please check latest version and report me if you have any suggestions.
