### ISSUE TITLE
Not working on remote host over ssh

### ISSUE THREAD

**Issue by dab** [syohex/emacs-helm-ag#122]
Hello here. Plugin working perfectly on local host, but still searching on local host even when projcetile root set to remote ssh. How to get it working over ssh?

**Comment by syohex** [comment]
I suppose that `helm-do-ag`(`helm-projectile-ag`) does not work on remote host with tramp.
I recommend you to use SSHFS or NFS instead of Tramp if you want to use those commands for remote files.

**Comment by dab** [comment]
Asked about 'helm-projectile-ag' — they told me that I should send you feature request.

**Comment by IvanMalison** [comment]
@syohex Would you be opposed to trying to do some type of remote command execution here. It might be tricky to set up, but I don't see a technical reason why it couldn't at least be attempted. We could put it behind a variable and leave it off by default.

**Comment by syohex** [comment]
I don't understand why `helm-do-ag` does not work with tramp yet.(`helm-ag` works well.). `helm-do-grep` works with tramp, I implemented `helm-do-ag` based on `helm-do-grep` however `helm-do-ag` does not work.

**Comment by syohex** [comment]
https://github.com/emacs-helm/helm/blob/81216449833dd0a28bf337bd423cec819c53c2e4/helm-grep.el#L868-L871

`helm-do-grep` cannot work `ack` on remote host. `ag` is similar to `ack`.
Can `ag` work on remote host ?

**Comment by syohex** [comment]
I think this issue was fixed with #149 changes.
Please check latest version.

**Comment by syohex** [comment]
Please reopen if you still have problem.
