### ISSUE TITLE
helm-ag doesn't work with -g option

### ISSUE THREAD

**Issue by lin2280778** [syohex/emacs-helm-ag#124]
use helm-ag$ -gnvm\*.c to search all c file contain nvm, return no output

use helm-ag$ -gnvm to search all file contain nvm, return nil nil nil nil nil nil nil

but these commands work in terminal:
ag -gnvm\*c
ag -gnvm

**Comment by syohex** [comment]
What do you expect by specifying `-g` option ?
`ag` with `-g` options outputs only file names.

> use helm-ag$ -gnvm*.c to search all c file contain nvm, return no output

Is this pattern right ? The pattern is PCRE, not shell glob. So this pattern matches
against `nvac`, `nvmmmmmmmmmmmmmmmmmmmmmmzc` etc. I suppose you should write
`nvm.*\.c` etc. In terminal, `*` may be expanded by shell.

> use helm-ag$ -gnvm to search all file contain nvm, return nil nil nil nil nil nil nil

`helm-ag` expects ouput whose style is grep format like `filename:line-number:matched line`.

**Comment by lin2280778** [comment]
thanks for replying. 

I want to use helm-ag to search files, for exemples, search all file names contain nvm.
then I can open the file by pressing RET.   A function like projectile-find-file

**Comment by syohex** [comment]
> I want to use helm-ag to search files, for exemples, search all file names contain nvm.
> then I can open the file by pressing RET. A function like projectile-find-file

`helm-projectile` provides such functions like `helm-projectile-find-file`.
What's difference between `helm-projectile` functions and yours ?

**Comment by lin2280778** [comment]
well...    I want a function exactly like helm-projectile-find-file but with ag.    for 2 reasons:
1) our project is too huge.  8G files.   ag is much faster than projectile.  ( is there a way to use ag for helm-projectile-find-file?)
2) I dont want to bind 2keys , one for projectile, one for ag.  if I can use one key for helm-ag, and with -g to search files, with -G to search strings, it's cool!

I have found other issue...  I want to use   helm-ag$ -G\.c$ string path to search string in c files in path, but it return no output "string path"... for exemple helm-ag$ -G\.c$ nvm /home/

**Comment by lin2280778** [comment]
sorry it's   helm-ag$ -G\.c$ nvm /home/

**Comment by lin2280778** [comment]
sorry it's helm-ag$ -G\\.c$ nvm /home/     there is a \ before .c

**Comment by syohex** [comment]
@lin2280778  I fixed for `-g` option specified case and I have merged it at #126. 
Please check latest version.

![](https://cloud.githubusercontent.com/assets/554281/8252211/9ec84056-16be-11e5-86cb-1cfa495f31f3.gif)
