### ISSUE TITLE
Is there anyway to show last search window?

### ISSUE THREAD

**Issue by goofansu** [syohex/emacs-helm-ag#137]
I want to see last search results sometimes, but cannot find any command doing this.

**Comment by syohex** [comment]
`M-x helm-resume`.

`C-u M-x helm-resume` if you executes a helm command other than `helm-ag` commands.

**Comment by goofansu** [comment]
Thank you very much. Not knowing this command before.

**Comment by cweiske** [comment]
I have to use `C-x c b` (which is the shortcut for `helm-resume`), because `M-x` starts a helm session itself :)
