### ISSUE TITLE
searching term with spaces produces a lot of results

### ISSUE THREAD

**Issue by cpaulik** [syohex/emacs-helm-ag#139]
Hi, This might be related to https://github.com/syohex/emacs-helm-ag/issues/78. 

When searching with `helm-do-ag` a ` ` in the search term causes a lot of results shown that seem unrelated.

I'm using spacemacs so this might be an issue there but I did not find any configuration in spacemacs that would obviously cause this.

Example:
I search the spacemacs source tree for `smooth scrolling`. Everything works fine when typing `smooth` showing me 23 results. But as soon as I type `smooth scroll` I get around 5000 results.

**Comment by syohex** [comment]
I cannot reproduce this issue with both ag(the silver searcher) and pt(the platinum searcher) as below.

![helm-ag](https://cloud.githubusercontent.com/assets/554281/8766041/67d0f148-2e64-11e5-8321-c46b69e8e725.gif)

Could you tell me your configuration about `helm-ag` ?

**Comment by cpaulik** [comment]
OK. Then this is probably a spacemacs configuration problem. I'll check it in more detail and see if I can pinpoint where the problem comes from.

**Comment by syohex** [comment]
This is ag version issue. I can reproduce this issue with ag version 0.19.2. However I cannot reproduce this issue with ag 0.30.0. Please update ag version and try again.

**Comment by cpaulik** [comment]
Thank you. This was the problem.

**Comment by cpbotha** [comment]
Thanks! I had exactly the same issue on Ubuntu 14.04 with its default silversearcher-ag package version of 0.19.2.

Installing 0.30.0 from this PPA https://launchpad.net/~gekkio/+archive/ubuntu/ag fixed it!
