### ISSUE TITLE
In the results buffer, the command is `nil`

### ISSUE THREAD

**Issue by thiderman** [syohex/emacs-helm-ag#144]
If in a session and I run `C-x C-s` to get into a results buffer, the title is always set to `nil` for me:

```
-*- mode: helm-ag -*-

Ag Results for `nil':

<results>```

I'm supposing there is a function to grab the command, and that doesn't work?

**Comment by syohex** [comment]
Thanks for reporting issue.
I have fixed at #145. Please check latest version.

**Comment by syohex** [comment]
Closed. Please report me if you still have problem.

**Comment by thiderman** [comment]
It works! Thanks a lot! :)
