### ISSUE TITLE
 helm-do-ag with  platinum doesn't work well on windows7 64bit

### ISSUE THREAD

**Issue by LuoPX-15510486969** [syohex/emacs-helm-ag#150]
helm-do-ag with  platinum work out the result but it dones't correct completely,.Please look at the screenshot below.  And what is the worst is that C-UP and C-DOWN dones.t work  when i navagate in helm session. So it doesn't show preview in work window.And when i press ENTER it do nothing in helm session.

my OS is windows7 64 bit  
helm-ag version 20150730 
platinum version is 1.7.8   
emacs version 24.5 with prelude.
![qq 20150803221718](https://cloud.githubusercontent.com/assets/13256245/9050265/8091989c-3a7e-11e5-8867-3447bb02b8c2.png)

**Comment by syohex** [comment]
Thanks for reporting. I fixed at #151. Please check latest version.

![helm-do-ag](https://cloud.githubusercontent.com/assets/554281/9054499/274230c8-3abd-11e5-8556-95f1f79ef7ca.gif)

**Comment by LuoPX-15510486969** [comment]
As you said It is OK now .Thanks a lot .

**Comment by syohex** [comment]
You are welcome.
