### ISSUE TITLE
how to preview searched file, but do not add it to buffers

### ISSUE THREAD

**Issue by xuxiangyang** [syohex/emacs-helm-ag#152]
Hi, I have a problem.
 
I searched something, helm-ag show many files, and I want auto preview file when I wander those files. I used C-j (helm-ag--persistent-action), this command create a new buffer, but I only want to see the file content, if it's that file I want to open, I could use C-j open it and add it to my buffers.

Is there some command I can use? I need some help, Thank you.

**Comment by xuxiangyang** [comment]
what I need may be show file content in temp-buffer, and I could decide if I need open the real file

**Comment by syohex** [comment]
> Is there some command I can use? I

No. There is no such command now.

**Comment by syohex** [comment]
I have added this feature at #156. Please check latest version with following configuration.

```lisp
(custom-set-variables
 '(helm-ag-use-temp-buffer t))
```

**Comment by xuxiangyang** [comment]
Thank you very much。。。

It's amazing ! ! ！

**Comment by xuxiangyang** [comment]
The newest version can not be installed from ELPA package manager?

**Comment by syohex** [comment]
Some hours are necessary until MELPA updates repositories. Please wait and retry. You can check it by [MELPA twitter account](https://twitter.com/melpa_emacs).
