### ISSUE TITLE
Original regex is not displayed correctly in the *helm ag results* buffer

### ISSUE THREAD

**Issue by whatyouhide** [syohex/emacs-helm-ag#158]
I often use `C-x C-s` to save the results of an `ag` search. I noticed the message at the top of the `*helm ag results*` buffer always says `nil` as the used regex, which I think is a bug:

<img width="829" alt="screen shot 2015-08-27 at 15 04 30" src="https://cloud.githubusercontent.com/assets/3890250/9521099/f3639b12-4ccc-11e5-8ea1-d20257a6570a.png">

I'm sorry I can't help with code but I have very little time these days and I'm not good at all at elisp :(

**Comment by syohex** [comment]
Do you use latest helm-ag ? This is similar to #144. And I fixed it.

**Comment by whatyouhide** [comment]
Hey @syohex, sorry it took me so long to respond. Ok, updated and everything works, I'm really sorry I didn't see the similar issue, I was in a hurry when I opened this one :( Thanks again!
