### ISSUE TITLE
Refresh results buffer

### ISSUE THREAD

**Issue by jonathanj** [syohex/emacs-helm-ag#173]
Saving the results to a buffer is very useful but unfortunately the search results can get stale quite quickly if you're using the results buffer to jump to files to make changes. I couldn't find a command that would do this, but it would be quite useful to be able to re-run the search that created the buffer and update the contents of the buffer, ie. "refresh".

Did I miss this feature somehow?

**Comment by syohex** [comment]
Could you check following patch ?

https://gist.github.com/syohex/a541fd987da35ec89a9e
(https://gist.githubusercontent.com/syohex/a541fd987da35ec89a9e/raw/fead8d4f3c71c5a77384bc52d032eb332ba4e57f/helm-ag-update.diff)

You can update by `g` key in saved buffer.

**Comment by jonathanj** [comment]
@syohex This works perfectly for me, thank you.

**Comment by syl20bnr** [comment]
Really nice feature :+1:

**Comment by syohex** [comment]
Merged.
