### ISSUE TITLE
remove line like `wgrep-mark-deletion`

### ISSUE THREAD

**Issue by jacobono** [syohex/emacs-helm-ag#175]
I just found this and I am loving it, thanks :+1: 

The edit feature is really nice, this only thing I am finding that I am missing from what I used to do with `wgrep` is marking a whole line for deletion.

I can do it manually with `C-k`, but that only kills the text, not the whole line like `wgrep-mark-deletion` does.

Do you have any ideas on how this could be accomplished?

**Comment by syohex** [comment]
See #178. I'm implementing.

**Comment by syohex** [comment]
I have merged. Please check latest version.
