### ISSUE TITLE
helm-ag package not available via melpa

### ISSUE THREAD

**Issue by dowcet** [syohex/emacs-helm-ag#179]
I am unable to install `helm-ag` using `package-install`. If I do a `package-list-packages` and do a search, I do not see it.

**Comment by syohex** [comment]
Did you add MELPA URL to package-archives as below ?

```lisp
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
```

**Comment by syohex** [comment]
Please see http://melpa.org/#/getting-started.

**Comment by dowcet** [comment]
My bad, thanks!
