### ISSUE TITLE
Use projectile (if available) to find project root 

### ISSUE THREAD

**Issue by iqbalansari** [syohex/emacs-helm-ag#180]
I think projectile has more sophisticated ways to find project root, this will also enable `helm-ag` to work on more projects

**Comment by syohex** [comment]
I suppose you should use `helm-projectile-ag` command in such case.

**Comment by iqbalansari** [comment]
Oh my bad, wasn't aware of that command, really sorry for the noise :pensive:

**Comment by syohex** [comment]
Thank you, but don’t bother.

**Comment by syohex** [comment]
You need to install helm-projectile package for using `helm-projectile-ag`.

**Comment by iqbalansari** [comment]
Just realized that the command is part of `helm-projectile`, that solves my problem. Just as a suggestion, I feel if `helm-ag` provides a command that searches in `projectile-root` users who do not have/want to install `helm-projectile` will find it useful.
