### ISSUE TITLE
Fails to open files with : in their names

### ISSUE THREAD

**Issue by peterhoeg** [syohex/emacs-helm-ag#181]
helm-ag is unable to open files that contain :. My guess is that it is  ```helm-ag--extract-file-and-line```` that fails.

If you have a file named ```some:file.yml```, when hitting enter on it, emacs will try to open just ```some``` instead of the whole file name.

**Comment by syohex** [comment]
See #182.

**Comment by syohex** [comment]
I have merged #182. Could you check latest version ? (You may need to wait some hours until MELPA update)

**Comment by syohex** [comment]
Please reopen if you still have problem. Thanks for reporting.

**Comment by peterhoeg** [comment]
Works, thanks for fixing it so quickly!
