### ISSUE TITLE
different results with ag, ack and pt

### ISSUE THREAD

**Issue by velkyel** [syohex/emacs-helm-ag#184]
```
Search Tips:

Pattern contains space

Pattern: foo bar baz

Search pattern is foo bar baz. You need not to wrap pattern with quotes.
```
after calling helm-do-ag:

with (helm-ag-base-command "ack --nocolor --nogroup") correctly (imo) find bazfoobar string (notice another order!), but
helm-ag-base-command "pt -e --nocolor --nogroup" or "ag --nocolor --nogroup" does not.  In advance ag settings often print "ERR: Too many matches in <somefile>. Skipping the rest of file" and dump rest of file into helm buffer.

**Comment by syohex** [comment]
Sorry its old implementation document, I have not updated it. Please use `\ `(backslash space) for searching pattern which contains spaces.

> In advance ag settings often print "ERR: Too many matches in . Skipping the rest of file" and dump rest of file into helm buffer.

It's `ag` limitation. You can avoid this issue by setting big number to `--max-count` option(default `10000`) or inputting long pattern.

**Comment by velkyel** [comment]
> Sorry its old implementation document, I have not updated it. Please use \(backslash space) for 
> searching pattern which contains spaces.

that's not what I thought.  If pattern is: **foo bar baz** then ack find **bazfoobar** string in files.. and that's correct I think.  In opposite pt or ag does not.  I'm not talking about hard spaces.

**Comment by syohex** [comment]
> In opposite pt or ag does not.

`ag` matches `bazfoobar` as below.

![test](https://cloud.githubusercontent.com/assets/554281/10941132/560511a4-834d-11e5-8eeb-0cfdd4deea0f.gif)

`pt` does not match `bazfoobar` because Golang regexp library does not implement look-a-head pattern.

**Comment by velkyel** [comment]
> ag matches bazfoobar as below. If you don't match, please upgrade ag and try again.

ah, there was my problem. Debian (even testing) has ag in version 0.26! I have just compile ag from github repo and it works much better.  Thank you.  closing
