### ISSUE TITLE
save helm-ag buffer to edit search results

### ISSUE THREAD

**Issue by tam17aki** [syohex/emacs-helm-ag#2]
In helm-do-grep, search results can be saved into *hgrep* buffer (helm-grep-mode).
In this buffer, a user can edit the search results via wgrep-helm.
I guess helm-ag can also support the same feature.
Moreover, it would be nice if candidates in *helm-ag* buffer are colored and highlighted, like grep, helm-occur, helm-ack, etc.

**Comment by 5t111111** [comment]
:+1: 
この機能があると嬉しいです。

**Comment by syohex** [comment]
Please check latest version. You can switch to edit mode by `C-c C-e`.
You edit something.

And you can save by `C-c C-c`(abort by `C-c C-k`)

**Comment by 5t111111** [comment]
Thank you!
Just FYI, although i really love this feature, unfortunately it seems doesn't work with helm-projectile, which tries to save files to wrong paths after editing them. Maybe i have to check how helm-ag is implemented in helm-projectile-ag later.

**Comment by syohex** [comment]
`default-directory` is not set correctly in `helm-do-ag`. I'll fix later.

**Comment by syohex** [comment]
@5t111111 Please check latest version. I fixed `helm-do-ag` issue at #70

**Comment by 5t111111** [comment]
I've confirmed the edited files are correctly saved with the latest version. I appreciate your quick fixes :smile:

**Comment by syohex** [comment]
Done

**Comment by Gastove** [comment]
Has there been a regression on this? I cannot seem to get `helm-ag-edit` to work.

I'm using helm, projectile, and helm-ag on Emacs 24.5. 

What I do: I call either `helm-projectile-ag` (defined in projectile) or `projectile-helm-ag` (defined by me using the helm-ag readme). I get a `helm-ag` buffer. I enter a search term, and get results. I hit `C-x C-s`, and the results are saved to a *helm ag results* buffer. So far, so good.

From here, however, I'm stuck. `C-c C-p` doesn't activate wgrep (expected). `C-c C-e` comes up unbound. Calling `M-x helm-ag-edit` throws the error, `No buffer named *helm*`. Inspecting the major mode claims that I'm in `helm-ag` mode. 

Suggestions? It *seems* like there's been a drift between the buffer name provided by `C-x C-s` and the buffer name `helm-ag-edit` is looking for.

**Comment by syohex** [comment]
> Has there been a regression on this?

No. `helm-ag` is not implemented as you expected now.

**Comment by Gastove** [comment]
Uh. Does editing an `ag` result work _at all_? It's still listed in the README.

**Comment by syohex** [comment]
> Does editing an ag result work at all?

It works, but saved buffer(`M-x helm-do-ag` -> `C-x C-s`) cannot be edited.


#### How to edit search result
1. Search with ag(`M-x helm-ag` or `M-x helm-do-ag`)
2. Switch to edit mode(Default `C-c C-e`)
3. Edit search result as you like
4. Save result(Default: `C-c C-c`)

Screencast is here.

![helm-ag](https://cloud.githubusercontent.com/assets/554281/7630050/43994288-fa6d-11e4-96fc-8bfe221f10b2.gif)
