### ISSUE TITLE
Ability to persist search buffer/ apply secondary filters

### ISSUE THREAD

**Issue by IvanMalison** [syohex/emacs-helm-ag#203]
This may be more of a helm feature request, but I think it would be nice to be able to do something where you say "I'm done running this ag search" but keep the buffer around.

**Comment by syohex** [comment]
Sorry I cannot understand your request. Could you tell me in more detail ?

**Comment by IvanMalison** [comment]
I want to be able to run a helm ag search and then freeze the state of the helm buffer so that i can manipulate it like a normal emacs buffer i.e do additional searching using something like helm-swoop or something like that.

**Comment by syohex** [comment]
Is it enough to `helm-resume` ?
