### ISSUE TITLE
How to ignore case when searching?

### ISSUE THREAD

**Issue by caisah** [syohex/emacs-helm-ag#204]
Hi,

I've started using `helm-ag` but I'm not able to ignore casing when searching. I have set `helm-ag--ignore-case` to `t` but it doesn't seem to work.

Do you know how I could fix this?

**Comment by syohex** [comment]
`helm-ag--ignore-case` is internal variable. You can archive this by following configuration.

```lisp
(custom-set-variables
 '(helm-ag-command-option "-i"))
```

Or you can input command option directly.

![orig](https://cloud.githubusercontent.com/assets/554281/12340547/d2f6774a-bb5e-11e5-91b7-9b19136a8910.gif)

**Comment by caisah** [comment]
Thanks, it works great!
