### ISSUE TITLE
Very slow on long lines?

### ISSUE THREAD

**Issue by isolet** [syohex/emacs-helm-ag#205]
Hi. I tried something like `helm-do-ag` on `~/.emacs.d/elpa` with patten `require`. But the live update seemed stuck in `elpa/archives/melpa/archive-contents` for seconds. Even after recovered continuing the search, the whole process seemed to be slowed down but finally completed. 

I tried the same command in terminal, the results come out immediately with the same result in `helm-do-ag`. The results of `helm-ag` in emacs also came out immediately. 

Is that really a issue or just the performance of emacs itself? 

Thanks.

**Comment by syohex** [comment]
> Is that really a issue or just the performance of emacs itself? 

Yes I think so.

**Comment by isolet** [comment]
Thanks for you comment.
