### ISSUE TITLE
Always enabled follow mode

### ISSUE THREAD

**Issue by gabrielsimoes** [syohex/emacs-helm-ag#207]
Is it possible to add a hook or something and make follow mode always enabled? Thanks in advance.

**Comment by syohex** [comment]
Yes, I've implemented this at #210. Thanks for suggestion. Please set `helm-follow-mode-persistent` to non-ni as below.

```lisp
(custom-set-variables
 '(helm-follow-mode-persistent t))
```

CAUTION. You need to set `helm-follow-mode-persistent` before loading helm-ag.el.

**Comment by gabrielsimoes** [comment]
Thanks! You may want to add it to the readme as well.
