### ISSUE TITLE
helm-do-ag ignores readme.md

### ISSUE THREAD

**Issue by gabrielsimoes** [syohex/emacs-helm-ag#208]
When running helm-do-ag on a project folder, it ignores readme.md. Is it a bug?

**Comment by syohex** [comment]
![readme](https://cloud.githubusercontent.com/assets/554281/12407353/070285f4-be9a-11e5-85ca-744cf413353f.gif)

I cannot reproduce this issue. I suppose you add `readme.md` to `.gitignore` or `.agignore`.

**Comment by gabrielsimoes** [comment]
You were right, my .gitignore had it, even though git was not ignoring it. Sorry for this.
