### ISSUE TITLE
Can't edit lines with -A -B -C

### ISSUE THREAD

**Issue by arturasz** [syohex/emacs-helm-ag#213]
If I use -C3 param I can only edit the line that had the search term in, but the lines before and after are read-only.

**Comment by syohex** [comment]
Sorry, helm-ag does not support `-A`, `-B`, `-C` options yet.

**Comment by syohex** [comment]
I have fixed this issue at #214. Please check latest version. Gif animation is here.

![edit-context](https://cloud.githubusercontent.com/assets/554281/12604884/e5807282-c502-11e5-8999-de9e15dde41a.gif)

**Comment by arturasz** [comment]
Hi, that was very fast, thank you. 
It might be something with my emacs, but If i have a file a.js

    b
    b
    aaa
    b
    b

and search for `aaa -C3`, I can only edit lines 2,3,5,6 while 1 and 4-th are not editable. Can you check if it works for you?

**Comment by syohex** [comment]
There is no not editable line on my environment.

![edit-test](https://cloud.githubusercontent.com/assets/554281/12609156/7ff9be84-c523-11e5-9dd0-df99406daa9c.gif)

There is no line 6 output. ag does not generate when it invokes within Emacs.

**Comment by syohex** [comment]
Please reopen if you still have problems.

**Comment by arturasz** [comment]
Works like a charm, thanks!
