### ISSUE TITLE
Changes in edit mode via helm-do-ag-this-file are not saved

### ISSUE THREAD

**Issue by wilkystyle** [syohex/emacs-helm-ag#218]
- **Emacs version:** 24.5.1
- **Operating system:** OSX 10.11.3 (El Capitan)
- **Search command:** `ag` v0.25.0

### Actual behavior

Content is _**not**_ saved to the file from edit mode when hitting `C-c C-c` to commit.

### Expected behavior

When when hitting `C-c C-c` to commit changes made in edit mode, the file would be updated and saved.

### Steps to reproduce

1. Open any file with text.
2. Run `M-x helm-do-ag-this-file`.
3. Enter any search term that causes results to appear, and hit `C-c C-e` to switch to edit mode.
4. Make any change to the text in edit mode, and hit `C-c C-c` to commit.
5. Observe that the file is unaltered.

**Comment by syohex** [comment]
Thanks for reporting issue. Please report me if you still problems.

**Comment by Jeff-avatar** [comment]
@syohex @wilkystyle I noticed that this issue was made in 2016, but I still encounter this issue now. I am on Mac OS 10.15.4 and my spacemacs version is 27.0.91. Do you know what I should do?  Thank you.

**Comment by syohex** [comment]
@Jeff-avatar I suppose your issue is fixed by #371. And please set `global-auto-revert-mode` if you don't enable it. I suppose current implementation required its configuration.

**Comment by Jeff-avatar** [comment]
> @Jeff-avatar I suppose your issue is fixed by #371. And please set `global-auto-revert-mode` if you don't enable it. I suppose current implementation required its configuration.

@syohex Thank you very much for your quick response. The fixes you just committed works for me now. I just modified the local helm-ag.el file according to your fixes. I am wondering if your fixes will automatically be applied to emacs when I reinstall emacs and helm-ag mode? In other words, if I install them on another computer, are your recent commits going to be obtained automatically?

**Comment by syohex** [comment]
> I am wondering if your fixes will automatically be applied to emacs when I reinstall emacs and helm-ag mode? In other words, if I install them on another computer, are your recent commits going to be obtained automatically?

I'm not sure what package manager you use, I suppose that you update package and byte-compile it then the fixes will be applied
