### ISSUE TITLE
Column is editable with helm-ag-edit

### ISSUE THREAD

**Issue by user471** [syohex/emacs-helm-ag#220]
- Emacs version
24.5.1
- Operating system
Windows 8.1
- Search command
ag version 0.29.1
- Last value of `helm-ag--last-command` `("ag" "--vimgrep" "foo")`

I have this file
```
foo
foo
foo
```
After `helm-ag` and `C-c C-e` the buffer looks like this

![1](https://cloud.githubusercontent.com/assets/5988253/14041851/d2bb1fac-f285-11e5-9631-a13264deae82.png)

And after `C-c C-c` file is changed to
```
1:foo
1:foo
1:foo
```

```
ag --vimgrep foo
test.js:1:3:1:foo
test.js:2:3:1:foo
test.js:3:3:1:foo
```

**Comment by syohex** [comment]
Thanks for reporting issue. I have fixed this issue at #223.
Its screenshot is here.

![vimgrep-option](https://cloud.githubusercontent.com/assets/554281/14075149/acde0e82-f511-11e5-9d72-2695bda8b8fa.png)

Please check latest version and report me if you still have problems.

**Comment by user471** [comment]
Thanks. It seems to work fine. Is it possible to remove `^M` as well?

**Comment by syohex** [comment]
@user471 I have fixed at `^M` issue on Windows at #225. Please check latest version.

**Comment by user471** [comment]
It doesn't work. I even tried to change https://github.com/syohex/emacs-helm-ag/blob/716f5215d47510b4980bb4f37e8541b65492da75/helm-ag.el#L239 to remove something else like `foo` but it doesn't remove anything.

**Comment by syohex** [comment]
Could you tell me value of `system-type` ?

**Comment by user471** [comment]
`windows-nt` 
`(helm-ag--windows-p)` works fine. 
If you replace `\xd` with `foo` and use `helm-ag` on file
```
foo1
foo2
```
would `helm` show you
```
1 
2
```
?

**Comment by syohex** [comment]
> If you replace \xd with foo and use helm-ag on file

What ? `"\xd"`(==`^M`) is replaced with `""`(empty string).

**Comment by user471** [comment]
Sorry. I mixed up with `helm-projectile-ag`. 
So, this problem have been fixed in `helm-ag` but somehow still exists in `helm-projectile-ag`. 
Do you know anything about this package?

**Comment by syohex** [comment]
Sorry I mistook removing carriage return in helm-do-ag command(which helm-projectile-ag uses). I have fixed it at #228.

**Comment by syohex** [comment]
Could you apply #228 change and retry ?

**Comment by user471** [comment]
It seems everything is working now, thanks.
