### ISSUE TITLE
You have to (must) escape spaces etc. if the pattern contains them

### ISSUE THREAD

**Issue by triklsbg** [syohex/emacs-helm-ag#221]
I think the Readme is not up to date.
*, ", blanks, minus, brackets, braces have to be escaped if they are searched literally.
- Emacs version 24.5.1
- Operating system arch-linux
- Search command(ag, pt, ack etc) and version: ag 0.31.0
- Last value of `helm-ag--last-command`

![screenshot_20160325_144011](https://cloud.githubusercontent.com/assets/3647083/14049686/2c55fc22-f2b7-11e5-93fb-f2c8efa493b1.png)

**Comment by syohex** [comment]
I have added explanation about this at #224.
Thanks for reporting.
