### ISSUE TITLE
How to if helm-ag search is complete

### ISSUE THREAD

**Issue by ratheesh** [syohex/emacs-helm-ag#229]
- Emacs version: 24.5.2
- Operating system: Linux
- Search command(ag, pt, ack etc) and version: ag
- Last value of `helm-ag--last-command`

Is there a way that user know that helm-ag has completed searching? This is important when large projects (eg. linux kernel source) is searched. Currently I look at the hard disk LED to know if the search has ended.

Can we do something like `helm-projectile-grep` do? It displays message in the helm modeline when search is complete.

**Comment by syohex** [comment]
`helm-do-ag` ? Or `helm-projectile-ag`(this command uses `helm-do-ag` internally) ?

**Comment by ratheesh** [comment]
It is `helm-projectile-ag`

**Comment by syohex** [comment]
Ah, sorry I misunderstood. I try to implement.

**Comment by ratheesh** [comment]
Working as expected. Closing this issue.
