### ISSUE TITLE
Feature request: customizable modeline after ag has finished searching

### ISSUE THREAD

**Issue by TheBB** [syohex/emacs-helm-ag#232]
Hi, I'm maintaining [Spaceline](https://github.com/TheBB/spaceline) where we have overridden Helm's modeline for one that looks a bit different. When the helm-ag process finishes, your library takes over. There seems to be no way to customize this.

https://github.com/syohex/emacs-helm-ag/blob/master/helm-ag.el#L861-L873

It would be great if the change to `mode-line-format` could optionally be turned off, and it would be even better if `helm-ag` could set a flag variable to indicate that the process had finished, which I could then read in my own code to provide the same feedback. I'd rather not have to advise this function.

**Comment by syohex** [comment]
I have merged #233.
