### ISSUE TITLE
Can't search 2 consecutive letters pattern

### ISSUE THREAD

**Issue by zhengpd** [syohex/emacs-helm-ag#235]
`helm-ag` triggers searching only for patterns more than 3 consecutive letters by default. How to make it for 2 letters? I don't see an option for this.

**Comment by syohex** [comment]
Please try following configuration.

```
(helm-attrset 'requires-pattern 2 helm-source-do-ag)
```

**Comment by zhengpd** [comment]
@syohex Great, that works. Thank you!
