### ISSUE TITLE
helm-do-ag with region

### ISSUE THREAD

**Issue by blaenk** [syohex/emacs-helm-ag#236]
I'm wondering if it would be possible to let the `helm-do-ag-*` family of functions pre-fill with the contents of the region, if there is one. I noticed by looking at the source that the `helm-ag-*` family of functions [do this](https://github.com/syohex/emacs-helm-ag/blob/master/helm-ag.el#L441-L447), and indeed I confirmed this is true when I do `helm-ag`. Perhaps there's a reason that this isn't done on the `helm-do-ag-*` functions, if so it's not a big deal to use `helm-ag` instead when I want this behavior, but I'm curious as to why it's not in `helm-do-ag-*`.

**Comment by syohex** [comment]
I have merged #237. Thanks for reporting.

**Comment by blaenk** [comment]
Thank you!

**Comment by blaenk** [comment]
It's working fine! Thanks again.

**Comment by blaenk** [comment]
I just realized that the region remains selected after choosing an ag search candidate, so that if the chosen candidate is within the same file, it ends up expanding the region selected since jumping to the candidate moves the cursor. I think the region should be ignored/deactivated if a candidate is chosen.

**Comment by syohex** [comment]
I have fixed it. Please check latest version.

**Comment by blaenk** [comment]
I can confirm it works. Thank you!
