### ISSUE TITLE
Unable to use helm-ag-edit after helm-resume

### ISSUE THREAD

**Issue by dvzubarev** [syohex/emacs-helm-ag#238]
- Emacs version: emacs-24.5.2, spacemacs-0.105.20
- Operating system: Ubuntu 16.04
- Search command(ag, pt, ack etc) and version: ag 0.31.0
- Last value of `helm-ag--last-command`
("ag" "--nocolor" "--nogroup" "--ignore" "TAGS" "--ignore" ".#*" "--ignore" "*.o" "--ignore" "*~" "--ignore" "*.bin" "--ignore" "*.lbin" "--ignore" "*.so" "--ignore" "*.a" "--ignore" "*.ln" "--ignore" "*.blg" "--ignore" "*.bbl" "--ignore" "*.elc" "--ignore" "*.lof" "--ignore" "*.glo" "--ignore" "*.idx" "--ignore" "*.lot" "--ignore" "*.fmt" "--ignore" "*.tfm" "--ignore" "*.class" "--ignore" "*.fas" "--ignore" "*.lib" "--ignore" "*.mem" "--ignore" "*.x86f" "--ignore" "*.sparcf" "--ignore" "*.dfsl" "--ignore" "*.pfsl" "--ignore" "*.d64fsl" "--ignore" "*.p64fsl" "--ignore" "*.lx64fsl" "--ignore" "*.lx32fsl" "--ignore" "*.dx64fsl" "--ignore" "*.dx32fsl" "--ignore" "*.fx64fsl" "--ignore" "*.fx32fsl" "--ignore" "*.sx64fsl" "--ignore" "*.sx32fsl" "--ignore" "*.wx64fsl" "--ignore" "*.wx32fsl" "--ignore" "*.fasl" "--ignore" "*.ufsl" "--ignore" "*.fsl" "--ignore" "*.dxl" "--ignore" "*.lo" "--ignore" "*.la" "--ignore" "*.gmo" "--ignore" "*.mo" "--ignore" "*.toc" "--ignore" "*.aux" "--ignore" "*.cp" "--ignore" "*.fn" "--ignore" "*.ky" "--ignore" "*.pg" "--ignore" "*.tp" "--ignore" "*.vr" "--ignore" "*.cps" "--ignore" "*.fns" "--ignore" "*.kys" "--ignore" "*.pgs" "--ignore" "*.tps" "--ignore" "*.vrs" "--ignore" "*.pyc" "--ignore" "*.pyo" "--ignore" ".idea/" "--ignore" ".eunit/" "--ignore" ".git/" "--ignore" ".hg/" "--ignore" ".fslckout/" "--ignore" ".bzr/" "--ignore" "_darcs/" "--ignore" ".tox/" "--ignore" ".svn/" "--ignore" ".stack-work/" "--ignore" "SCCS" "--ignore" "RCS" "--ignore" "CVS" "--ignore" "MCVS" "--ignore" ".svn" "--ignore" ".git" "--ignore" ".hg" "--ignore" ".bzr" "--ignore" "_MTN" "--ignore" "_darcs" "--ignore" "{arch}" "--" "Backend")

### Actual behavior
After using helm-resume, I press C-c C-e and it results in "C-c C-e is undefined"
### Expected behavior
C-c C-e leads to editable buffer
### Steps to reproduce
- M-x helm-do-ag
- search something
- press < esc >
- M-x helm-resume
- C-c C-e

**Comment by syohex** [comment]
Thanks for reporting issue. I have fixed this issue at #240. Please check latest version. (You need wait to some hours if you download helm-ag from MELPA).

**Comment by dvzubarev** [comment]
Thank you, works fine for me.
