### ISSUE TITLE
Pattern starting with -- is interpreted as option

### ISSUE THREAD

**Issue by greenrd** [syohex/emacs-helm-ag#239]
- Emacs version: 24.5.1
- Operating system: Windows 10
- Search command(ag, pt, ack etc) and version: ag version 0.29.1
- Last value of `helm-ag--last-command`: `("ag" "--vimgrep" "--refresh-config" "")`

### Actual behavior
`helm-ag--init: Failed: ''`

### Expected behavior
Find all occurrences of the text "--refresh-config" (i.e. not interpret it as an option to ag)

### Steps to reproduce
`M-x helm-ag`
`--refresh-config`

**Comment by syohex** [comment]
Please input `-- --refresh-config` same as command line. Patterns after `--` are not treated as command line options.
