### ISSUE TITLE
[Feature request] Add ivy support

### ISSUE THREAD

**Issue by zilongshanren** [syohex/emacs-helm-ag#243]
Recently I have totally switched from helm to ivy,  just because ivy has better performance than helm and it's light weight.

But one thing I missed the most after switching to ivy for a month is the missing of `emacs-helm-ag`, there is no replacement right now.

Could you  provide a completion option for ivy ?

Thanks.

**Comment by syohex** [comment]
`counsel-ag` provides `ag` frontend with `ivy` completion. And you can edit search result with wgrep mode.

See also
- http://oremacs.com/2016/04/26/ivy-0.8.0/ (Many improvements to ivy-occur-mode)

**Comment by zilongshanren** [comment]
@syohex 

I  know `counsel-ag`, but it can't filter result like `helm-ag` does... I can't use `!keyword` to exclude some results in the search buffer...

And the search keyword seems order matters, I really like the way `helm-ag` does.

**Comment by syohex** [comment]
helm-ag depends on helm heavily so it is difficult to support other completion framework.
If you want to need only its feature, I suppose you should send PR to counsel. `!` feature is not difficult to implement. helm-ag converts from `!pattern` to `^(?!pattern).*$`.

See also
- http://www.regextester.com/15
- http://www.regular-expressions.info/lookaround.html

**Comment by zilongshanren** [comment]
@syohex 
Thanks, I will consider to find a workaround with `counsel-ag`.
