### ISSUE TITLE
show history of previous commands when executing helm-do-ag

### ISSUE THREAD

**Issue by mstorus** [syohex/emacs-helm-ag#244]
```
- Emacs version
GNU Emacs 24.5.1 
- Operating system
OS X 10.10.5 (14F1713)
Darwin 14.5.0
- Search command(ag, pt, ack etc) and version
ag version 0.31.0
Features:
  +jit +lzma +zlib
- Last value of `helm-ag--last-command`
("ag" "--nocolor" "--nogroup" "--" "MySearchTerm")
```

### Actual behavior
When executing helm-do-ag, I enter the search directory, extra options, and then the search term. Results are displayed in the helm buffer. 
I may press `C-z` or `C-j` to preview a match, and then I may press RET to visit a file, which closes the helm buffer.
Later on, if I want to repeat my search, I'm required to enter the search directory, extra options, and the search term again from scratch.

### Expected behavior
I would like to have a way to easily repeat my previous search.
One possibility would be to pre-fill the search directory, extra options, and the search term with the previous text.

Another possibility is for each of `helm-do-ag` to show a history of previously used selections. For example, the search directory step could show a list of previous search directories, then the extra options step could show a history of previous extra options, and finally the search term step could show a history of previous search terms.

Or finally, a totally different solution would be to allow me to visit a file from the helm buffer, while keeping the helm available in the background so that I can return to it later. For example, I could press RET on a search result, but then later on I could go back to the active helm buffer using `C-x b`

### Steps to reproduce
M-x hel-do-ag
enter directory
enter extra options
enter search term
select a match by pressing RET (helm buffer is closed)

**Comment by syohex** [comment]
Please try `M-x helm-resume`. If you call other helm-command after calling helm-do-ag, then please use `C-u M-x helm-resume`.

**Comment by mstorus** [comment]
@syohex perfect, thank you!

**Comment by syohex** [comment]
You are welcome.
