### ISSUE TITLE
After edited and saved changes, emacs keep opened all buffers where search occurences were found

### ISSUE THREAD

**Issue by sandric** [syohex/emacs-helm-ag#246]
- Emacs version 25.1.50
- Operating system OSX
- Search command(ag, pt, ack etc) and version PT 
- Last value of `helm-ag--last-command`

### Actual behavior
If you start searching in directory and find occurences in different files. Then you edit results and save (commit) changes - you returns to your start buffer with changes applied, but if you open helm-mini you can see that all files where occurences were also found but where there was no changes are opened.

### Expected behavior
To close all buffers that where spawned after search command was entered and edit was called.

### Steps to reproduce
Start helm-find-files, enter query, with many found files enter edit-mode, edit some line in one of files, call helm-ag--edit-commit command to save changes, open helm-mini and observe buffer list

**Comment by syohex** [comment]
I have sent PR at #248. Please check it.

**Comment by syohex** [comment]
I have fixed at #248 and merge it into master branch. Please check latest version.
Thanks for reporting issue.

**Comment by sandric** [comment]
I already fixed that with little function, but and now I can remove that with your fix, thanks!
