### ISSUE TITLE
[Feature request] Add default action to edit results

### ISSUE THREAD

**Issue by toupeira** [syohex/emacs-helm-ag#249]
I find myself frequently using the very awesome `helm-ag-edit` to edit the search results, would you consider adding it as a default Helm action so I can just hit F4?

**Comment by vemv** [comment]
Hi there,

how can I to the edit action the default one? So I just hit tab instead of f4

**Comment by vemv** [comment]
(I meant RET not tab)

**Comment by vemv** [comment]
Attempted this by just overriding the defvars:

```
;; redefine for having just one action

(setq helm-ag--actions
  (helm-make-actions
   "Edit search results"    #'helm-ag--edit))

;; redefine for using the redefined helm-ag--actions

(setq helm-ag-source
  (helm-build-in-buffer-source "The Silver Searcher"
    :init 'helm-ag--init
    :real-to-display 'helm-ag--candidate-transformer
    :persistent-action 'helm-ag--persistent-action
    :fuzzy-match helm-ag-fuzzy-match
    :action helm-ag--actions
    :candidate-number-limit 9999
    :keymap helm-ag-map
    :follow (and helm-follow-mode-persistent 1)))
```

But it doesn't have an effect.

Could you consider making this easily configurable?

**Comment by vemv** [comment]
I had `setq helm-source-do-ag` too.

Working now!

Sorry for the noise. Still, if possible please make this configurable so I don't have to maintain these hacks which can get out of date
