### ISSUE TITLE
helm-swoop and helm-ag

### ISSUE THREAD

**Issue by yuandaxing** [syohex/emacs-helm-ag#252]
helm-ag is really awesome for multiple file editing of the search result, i love it!
and i use helm-swoop for multiple buffer editing of the search result, 
helm-swoop support context, like, "--after-context" of grep.
can helm-ag do the same thing? and support edit.

**Comment by syohex** [comment]
Sorry for late reply. You can use `-A`, `-B`, `-C` option.

![context-option](https://cloud.githubusercontent.com/assets/554281/16525556/fc7fe408-3fe7-11e6-9806-b7547e49d8de.gif)

**Comment by yuandaxing** [comment]
Awesome.

**Comment by arichiardi** [comment]
Wow this is really neat!
