### ISSUE TITLE
helm-ag-insert-at-point could not work well.

### ISSUE THREAD

**Issue by yuandaxing** [syohex/emacs-helm-ag#253]
below is my config:
(use-package helm-ag
  :ensure t
  :config
  (require 'helm-ag)
  (setq  helm-ag-insert-at-point 'symbol)
)

when i place my cursor in some symbol, and run helm-do-ag
if i type C-c C-e, i could not edit, but if i type something, for example "space"
then i could type C-c C-e to edit.
could you please help to fix this bug?

**Comment by syohex** [comment]
Thanks for reporting issue. I suppose this is helm issue. However I have applied workaound at #256. Please check latest version.
