### ISSUE TITLE
Bind ag search in concrete fixed directory

### ISSUE THREAD

**Issue by rsuhada** [syohex/emacs-helm-ag#254]
I can't figure out how to bind helm-ag to be run in a specific, hard coded directory. Example: I'd like helm-ag to search in ~/org/ if I hit M-F6 independently where the current file is. My "guess" below doesn't work.

    (use-package helm-ag
      :ensure t
      :config
      (custom-set-variables
       '(helm-ag-base-command "ag --ignore-case --nogroup")
       '(helm-ag-command-option "--all-text ~/org/")
       ;; '(helm-ag-insert-at-point 'symbol)
       )
      :bind
      (
       ("<M-f6>" . helm-ag '("~/org"))
       )
      )

Is this possible? What if I want to run it on a list of directories (~/org and ~/documents/)? 

Thank you very much!

**Comment by syohex** [comment]
Sorry late reply. You can write following command for searching at a specified directory. Or you can also use `C-u` prefix for `helm-ag`, then helm-ag asks you searched directory.

```lisp
(defun my/helm-ag ()
  (interactive)
  (let ((default-directory (expand-file-name "~/org/")))
    (call-interactively #'helm-ag)))
```

> What if I want to run it on a list of directories (~/org and ~/documents/)? 

Sorry no way for searching from multiple directories now.

**Comment by rsuhada** [comment]
Thank you very much for the help!
