### ISSUE TITLE
When `helm-ag-command-option` is set to non-nil, helm-ag* commands forget .gitignore

### ISSUE THREAD

**Issue by rsuhada** [syohex/emacs-helm-ag#255]
When `helm-ag-command-option` is set to non-nil, helm-ag* commands forget to ignore things in .gitignore.

Setting:

> (custom-set-variables
>    '(helm-ag-base-command "ag --nocolor --nogroup --ignore-case")
>    '(helm-ag-command-option "--all-text")
>    '(helm-ag-insert-at-point 'symbol))

Causes helm-ag to searh also files/dirs that are listed in .gitignore.

Thank you very much!

**Comment by syohex** [comment]
`--all-text` option ignores `.gitignore`.
