### ISSUE TITLE
Follow mode and output formatting

### ISSUE THREAD

**Issue by quicknir** [syohex/emacs-helm-ag#257]
Hello,

I was working on a pull request to use swoop for multi buffer search in spacemacs instead of helm-ag which is used currently. When doing so, though, I noticed that helm-ag is much much faster. I was thinking then that maybe instead of switching to swoop, the couple of minor of advantages of swoop could be brought to helm-ag.

The first of these is follow mode. Helm has follow mode of course, and it has a variable that persists follow mode. But this is shared between helm sessions, and follow mode is quite poor when searches on disk are performed (as follow mode can cause tons of buffers to get opened and is slow). Is there a way to write a function which calls helm-ag with follow mode activated, without affecting anything else?

Second; if you compare swoop & helm ag, the output is formatted rather differently. In helm-ag, the filename and line number are on the left of every line, followed by the match. In swoop, it lists the file names in a clear separate font on their own line separating results, which then only have line number + text. Would it be possible to implement this? Maybe as an option, if you think that not everyone will think it's nicer?

Personally I think that #2 would also be really nice for on disk ag searches.

Edit: There's actually a third thing I realized. Helm swoop has an option that enables syntax highlighting in the searched buffer. This is actually extremely powerful, it makes it much easier to read the searched buffer.

**Comment by syohex** [comment]
> Is there a way to write a function which calls helm-ag with follow mode activated, without affecting anything else?

No. Its behavior is defined at loading time. However you can enable helm-follow-mode by `C-c C-f`.

> Would it be possible to implement this? Maybe as an option, if you think that not everyone will think it's nicer?

No.

**Comment by quicknir** [comment]
In the end it was possible, took a bit of digging.

```
  (defun my-ag ()
    (interactive)
    (let ((prev-follow-val (helm-get-attribute-from-source-type 'follow helm-source-do-ag)))
      (helm-attrset 'follow 1 helm-source-do-ag)
      (call-interactively 'helm-do-ag-buffers)
      (helm-attrset 'follow prev-follow-val helm-source-do-ag)
      )
    )
```

For the second, you think it's impossible to implement, you don't want to do it, or you don't think it's a good thing? I want to know whether to possibly tackle this as a pull request.

I declared surrender on the third because syntax highlighting in emacs has issues.

**Comment by syohex** [comment]
> For the second, you think it's impossible to implement, you don't want to do it, or you don't think it's a good thing?

I don't want it.  I think it is enough to use `C-c C-f` or enable follow-mode as default by each user. If you want to implement it, please write code like your example.

**Comment by quicknir** [comment]
Sorry I'm having trouble understanding. As far as follow mode goes, I understand you're not excited about this option, and I found a way to implement it as a user, so that's resolved from my perspective.

The other question was about output formatting. helm-ag currently does this:

```
<file1><lineno><line>

**Comment by syohex** [comment]
> Do you think this is impossible?
> You think it's possible but you don't want it in helm-ag even as an option (even if I put in a pull request)? 

Yes it is possible. But I don't want to it. I like `grep` format. I think it is difficult to understand which file is current matched line if many lines(ex, 100-1000) in a file are matched. While `grep` format, user can understand it easily. And it requires a lot of code and it makes me difficult to maintain code. sorry.
