### ISSUE TITLE
sometimes helm-ag cannot work in gbk file

### ISSUE THREAD

**Issue by lxnow321** [syohex/emacs-helm-ag#259]
init.el
...
(set-language-environment 'Chinese-GBK)
(modify-coding-system-alist 'file "\\.py\\'" 'gbk)
...

Create a new python file, the encode must be gbk.
normal:
![1](https://cloud.githubusercontent.com/assets/6749770/17009148/774040b0-4f2a-11e6-817b-7553f63e4498.png)

abnormal
![2](https://cloud.githubusercontent.com/assets/6749770/17009161/9b0b285c-4f2a-11e6-974e-705cfc22c990.png)

I test it in win7 and ubuntu.I have no idea to solve it, can you help me?Thank you.

**Comment by syohex** [comment]
Could you check whether it works on terminal, for example `ag def` ? If it does not works on terminal too, it is `ag` issue. (`ag` may treat it as binary file).

**Comment by lxnow321** [comment]
Thank you for your help.
The problem really is from the ag.
I try to use "ag def" for my python file, it cannot work.
Thank you for helm-ag,I love it.
:+1:

**Comment by syohex** [comment]
You are welcome.
