### ISSUE TITLE
helm-do-ag support multiple directory search

### ISSUE THREAD

**Issue by yuandaxing** [syohex/emacs-helm-ag#264]
helm-do-grep support multiple  directory search, below it is called "TARGETS".

helm-do-grep-1 is a compiled Lisp function in `helm-grep.el'.

(helm-do-grep-1 TARGETS &optional RECURSE ZGREP EXTS DEFAULT-INPUT
INPUT)

I want to customize helm-do-ag to support multiple directory search.

**Comment by syohex** [comment]
You can select multiple directories by `Ctrl-space` and marking them however directories must be in current directory.

And `helm-do-ag` can take `targets` argument as below.

```lisp
(helm-do-ag default-directory (list some-dir1 some-dir2))
```

**Comment by deb0ch** [comment]
When you do that it works, but what feels very odd is that the displayed pathnames are all relative to whichever directory that you marked without displaying it, so you don't really know which candidate is from which directory.

Is there a way around that ?

**Comment by AtomicNess123** [comment]
I would like to search with helm-do-ag in several paths. Is there a way to do it interactively or I need to set a function for it?

**Comment by AtomicNess123** [comment]
> When you do that it works, but what feels very odd is that the displayed pathnames are all relative to whichever directory that you marked without displaying it, so you don't really know which candidate is from which directory.
> 
> Is there a way around that ?

Did you find an answer for this?
