### ISSUE TITLE
allow double dash options

### ISSUE THREAD

**Issue by st-anastasia** [syohex/emacs-helm-ag#265]
- Emacs 24.5
- Mac OS X 0.11.6 El Capitan
- ag, the_silver_searcher: stable 0.32.0

`(define-package "helm-ag" "20160809.337" "the silver searcher with helm interface" '((emacs "24.3") (helm "1.7.7")) :url "https://github.com/syohex/emacs-helm-ag")`

### Actual behavior
helm-ag ignore options starting with double dash, e.g  --ignore PATTER

### Expected behavior
Some ag options have no shortcut with one dash. Helm-ag should allow to specify
double dash options

### Steps to reproduce
--ignoremd foo 
 will show undefined option --ignoremd

where for example searching in md files only works fine with
--Gmd foo

**Comment by syohex** [comment]
You mistook to specify option. You should input like `--ignore=*.md foo`, not `--ignoremd`.
And helm-ag already supports double dash options. Please check by inputting `--help `

**Comment by dre-hh** [comment]
thx, (posted from different computer/account)
--ignore=*.md  is working fine, 
though -Gmd and -G=*md are working both 
and the README only showed the syntax without equals
shell i, add the syntax with equals to the doc?

**Comment by syohex** [comment]
No. It is just `ag` option. I suppose it is enough to see ag manual.
