### ISSUE TITLE
Hanging process on emacs 25.1-1

### ISSUE THREAD

**Issue by hung-phan** [syohex/emacs-helm-ag#271]
- Emacs version: 25.1-1
- Operating system: MacOSX Serria
- Search command(ag, pt, ack etc) and version: ag 0.32.0
- Last value of `helm-ag--last-command`: Doesn't exist this command

### Actual behavior
The emacs is hanging when typing helm-ag then value to search

### Expected behavior
Not hanging

### Steps to reproduce
Current repo: https://github.com/hung-phan/.emacs.d

Helm ag config:

```
(custom-set-variables
 '(helm-ag-base-command "ag --nocolor --nogroup --ignore-case")
 '(helm-ag-command-option "--all-text")
 '(helm-ag-insert-at-point 'symbol))
```

**Comment by syohex** [comment]
I cannot reproduce.

**Comment by hung-phan** [comment]
Already fixed. Conflict with other plugins.
