### ISSUE TITLE
Support for ripgrep?

### ISSUE THREAD

**Issue by x-ji** [syohex/emacs-helm-ag#272]
There is a new search tool called [`ripgrep`](http://blog.burntsushi.net/ripgrep/) released by the author of Rust's regex tools, burntsushi, which sounds quite promising and supports Windows as well. Maybe somebody can consider adding support for that in `emacs-helm-ag`?

**Comment by syohex** [comment]
I've test. `helm-ag` works, but `helm-do-ag` does not work. `--vimgrep` option does not work on `helm-do-ag`.

**Comment by syohex** [comment]
It looks ripgrep works with following configuration.

```lisp
(setq helm-ag-base-command "rg --vimgrep --no-heading")
```

**Comment by syohex** [comment]
I added document.
