### ISSUE TITLE
--ignore flag not supported

### ISSUE THREAD

**Issue by deb0ch** [syohex/emacs-helm-ag#274]
Including `--ignore PATTERN` in the search doesnt work.

When looking at the variable `cmd-args` in helm-ag.el:989, the command looks like that:

input: `keyword1 keyword2 --ignore PATTERN`

cmd-args: `(ag --nocolor --nogroup --ignore (?=.*keyword1.*)(?=.*keyword2PATTERN.*))`

With `-G`, which was recently fixed, it works by sticking them together like `-GPATTERN`, but that doesnt work for `--ignore` as `--ignorePATTERN` gives an error.

**Comment by syohex** [comment]
Please input `--ignore=pattern`. This is limitation now. I'll try to improve code.

**Comment by deb0ch** [comment]
Oooooooooooh I so didn't think of using `=` :dizzy_face:

Thanks for your answer :smile:

**Comment by syohex** [comment]
It is difficult to support space separator because all long options don't take values. So please use `=` separator always. I'll update document.

**Comment by deb0ch** [comment]
Ok. Would it be too difficult to have a list of "argumented" options, for example because of incompatibilities between search tools or so ?

If there is no major issue with that approach, or if you don't have time for it yourself maybe somebody else (I, for instance) could develop that feature ?

Let me know if you are open to that :smile:
