### ISSUE TITLE
Helm ag result saved buffer is not getting shown on helm-buffers and helm-mini.

### ISSUE THREAD

**Issue by rajats105** [syohex/emacs-helm-ag#282]
- Emacs version
   GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57) of 2015-04-14
- Operating system
   Mac OS X 10.11.6
- Search command(ag, pt, ack etc) and version
   ag version 0.32.0

   Features:
     +jit +lzma +zlib

- Last value of `helm-ag--last-command`

### Actual behavior
Helm ag result saved buffer is not getting shown on `helm-buffers` and `helm-mini`.
It is shown on `ibuffer`.

### Expected behavior
Helm ag result saved buffer should be shown on `helm-buffers` and `helm-mini`.

### Steps to reproduce
- Do helm-do-ag for anything.
- Save the result in a buffer.
- Try switching to the buffer from another buffer.

**Comment by syohex** [comment]
It is `helm-boring-buffer-regexp-list` issue. Such commands ignore buffers which are matched against `helm-boring-buffer-regexp-list`.  Please check its value.

**Comment by rajats105** [comment]
You are right, the list has `"\\*helm"`.

To fix this I have added `(setq helm-white-buffer-regexp-list '("\\*helm ag results"))` to my emacs config.
