### ISSUE TITLE
Emacs freeze after input some pattern with helm-ag

### ISSUE THREAD

**Issue by merrickluo** [syohex/emacs-helm-ag#288]
- Emacs version 
25.1.1  from https://emacsformacosx.com/
- Operating system 
macOS 10.12.2
- Search command(ag, pt, ack etc) and version 
ag 1.0.2
pt 2.1.5
- Last value of `helm-ag--last-command`
Cannot get that because Emacs freeze and consumes 100% cpu, I had to force close it.

### Actual behavior
Emacs freeze and consumes 100% cpu.

### Expected behavior
Work as normal.

### Steps to reproduce
1. Open Emacs.app
1. M-x helm-ag
1. input any string
1. emacs freeze

Other: 
1. M-x ag works fine

**Comment by syohex** [comment]
I cannot reproduce this issue as below. Could you reproduce this issue with minimum configuration ?

![helm-ag-mac](https://cloud.githubusercontent.com/assets/554281/22024100/2c20d660-dd0c-11e6-9467-093486513fd3.gif)

**Comment by merrickluo** [comment]
It seems broke by this [Fira Code ligature settings](https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs), and there is already an issue there https://github.com/tonsky/FiraCode/issues/100, sorry for the disturbance and thanks for your time! Closing this I think...
