### ISSUE TITLE
Error running timer

### ISSUE THREAD

**Issue by asimisoft** [syohex/emacs-helm-ag#291]
I am using `emacs 25.1 (9.0)`, `mac osx yosemite`,  `helm-ag 0.57``

I just installed `helm-ag` and try to search for some words in current file, and getting error:

![screen shot 2017-02-08 at 11 48 53 am](https://cloud.githubusercontent.com/assets/14917043/22725294/aaaa963a-edf4-11e6-9a8e-8a0e6284a010.PNG)

Also see this screencast for what exactly is happening:

![helm-ag-error](https://cloud.githubusercontent.com/assets/14917043/22725329/e8f53558-edf4-11e6-91de-4f711d31400d.gif)

**Comment by syohex** [comment]
Did you install `ag` command ?

**Comment by asimisoft** [comment]
@syohex yes, I have installed `ag` command using `melpa`.

**Comment by syohex** [comment]
No. It is ag.el package. I mean https://github.com/ggreer/the_silver_searcher

**Comment by asimisoft** [comment]
Yes, I had already installed it using `home brew`.

```sh
brew install the_silver_searcher

...
Warning: the_silver_searcher-1.0.2 already installed
```

**Comment by syohex** [comment]
Can you see `ag` from Emacs ? `M-: (executable-find "ag")`

**Comment by syohex** [comment]
Please set PATH environment variable and `exec-path`. I recommend you to use [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell)

**Comment by asimisoft** [comment]
@syohex: 👍 

Thank you very much for you help. Adding https://github.com/purcell/exec-path-from-shell did solved this issue as well as some weird issues I was getting in my zsh terminal.
