### ISSUE TITLE
rg --vimgrep shows multiple lines

### ISSUE THREAD

**Issue by agriffis** [syohex/emacs-helm-ag#293]
- Emacs 25.1.1
- Fedora 25
- ripgrep 0.3.2
- `helm-ag--last-command` is `("rg" "--smart-case" "--no-heading" "--vimgrep" "asdf")`

### Actual behavior
multiple lines returned for a single line containing multiple instances of the same value

![screenshot from 2017-02-17 11-37-32](https://cloud.githubusercontent.com/assets/50637/23074130/e3aec362-f505-11e6-9c94-27aa5f4e04c5.png)

### Expected behavior
just show one result, like ag does

### Notes
helm-ag has this code for ag:

```emacs
(defcustom helm-ag-base-command
  (if (helm-ag--windows-p)
      "ag --vimgrep"
    "ag --nocolor --nogroup")
  "Base command of `ag'"
  :type 'string)
```

I'm not sure why this uses `--vimgrep` on Windows and not on other platforms, but it could be the reason for the discrepancy we're seeing between `ag` and `rg`. What do you recommend?

### References
https://github.com/syl20bnr/spacemacs/issues/7370#issuecomment-280681995

**Comment by syohex** [comment]
This is `--vimgrep` specification. You can get same result without Emacs and helm-ag. If you don't like that behavior, please remove `--vimgrep` option and try. However I don't know ripgrep well and I don't know helm-ag work without it option.

> I'm not sure why this uses --vimgrep on Windows and not on other platforms, but it could be the reason for the discrepancy we're seeing between ag and rg. What do you recommend?

helm-ag expects search program(`ag`, `rg` etc) always show filename and line number and matched line(For example, `test.el:83: asdf foo bar baz`. We should set command line options for getting such output.

`ag` sometimes does not show filename on Windows , while Linux and macOS works as expected with same option. I don't understand why ag does not work on windows. `--vimgrep` option always show file name, so I set it for windows environment.

**Comment by agriffis** [comment]
@syohex Thanks for the explanation of why you're setting `--vimgrep` on Windows. I think that makes it clear that we don't need to set it for ripgrep.

**Comment by agriffis** [comment]
Thanks for your help, I think we're all set here :-)

**Comment by Davidj361** [comment]
I'm confused. I'm on windows so I'm using --vimgrep, but helm-ag seems to only work with --vimgrep. However I get multiple matches per a line which is hell to scroll through.

**Comment by syohex** [comment]
Can you use `--with-filename`(`-H`) option instead of `--vimgrep` option ?

**Comment by Davidj361** [comment]
Nothing is showing:
Last ag command:
```
("ag" "-H" "--ignore" "TAGS" "--ignore" ".#*" "--ignore" "*.o" "--ignore" "*~" "--ignore" "*.bin" "--ignore" "*.bak" "--ignore" "*.obj" "--ignore" "*.map" "--ignore" "*.ico" "--ignore" "*.pif" "--ignore" "*.lnk" "--ignore" "*.a" "--ignore" "*.ln" "--ignore" "*.blg" "--ignore" "*.bbl" "--ignore" "*.dll" "--ignore" "*.drv" "--ignore" "*.vxd" "--ignore" "*.386" "--ignore" "*.elc" "--ignore" "*.lof" "--ignore" "*.glo" "--ignore" "*.idx" "--ignore" "*.lot" "--ignore" "*.fmt" "--ignore" "*.tfm" "--ignore" "*.class" "--ignore" "*.fas" "--ignore" "*.lib" "--ignore" "*.mem" "--ignore" "*.x86f" "--ignore" "*.sparcf" "--ignore" "*.dfsl" "--ignore" "*.pfsl" "--ignore" "*.d64fsl" "--ignore" "*.p64fsl" "--ignore" "*.lx64fsl" "--ignore" "*.lx32fsl" "--ignore" "*.dx64fsl" "--ignore" "*.dx32fsl" "--ignore" "*.fx64fsl" "--ignore" "*.fx32fsl" "--ignore" "*.sx64fsl" "--ignore" "*.sx32fsl" "--ignore" "*.wx64fsl" "--ignore" "*.wx32fsl" "--ignore" "*.fasl" "--ignore" "*.ufsl" "--ignore" "*.fsl" "--ignore" "*.dxl" "--ignore" "*.lo" "--ignore" "*.la" "--ignore" "*.gmo" "--ignore" "*.mo" "--ignore" "*.toc" "--ignore" "*.aux" "--ignore" "*.cp" "--ignore" "*.fn" "--ignore" "*.ky" "--ignore" "*.pg" "--ignore" "*.tp" "--ignore" "*.vr" "--ignore" "*.cps" "--ignore" "*.fns" "--ignore" "*.kys" "--ignore" "*.pgs" "--ignore" "*.tps" "--ignore" "*.vrs" "--ignore" "*.pyc" "--ignore" "*.pyo" "--ignore" "{arch}" "--ignore" "_darcs" "--ignore" "_MTN" "--ignore" ".bzr" "--ignore" ".hg" "--ignore" ".git" "--ignore" ".svn" "--ignore" ".src" "--ignore" "MCVS" "--ignore" "CVS" "--ignore" "RCS" "--ignore" "SCCS" "--ignore" ".idea/" "--ignore" ".ensime_cache/" "--ignore" ".eunit/" "--ignore" ".git/" "--ignore" ".hg/" "--ignore" ".fslckout/" "--ignore" "_FOSSIL_/" "--ignore" ".bzr/" "--ignore" "_darcs/" "--ignore" ".tox/" "--ignore" ".svn/" "--ignore" ".stack-work/" "--ignore" "*.zip" "input" "./")
```

**Comment by syohex** [comment]
```lisp
(setq helm-ag-base-command "rg --with-filename --line-number" )
```

How about `--with-filename` and `--line-number` as above ? It works on my Windows machine.

**Comment by Davidj361** [comment]
Oh my mistake, if I do from M-x helm-do-ag then it works, same with projectile-ag when done from M-x. But when I do C-c p s s for initiating projectile-ag, it doesn't work.
