### ISSUE TITLE
Helm-ag / helm-projectile-ag seems to ignore .agignore 

### ISSUE THREAD

**Issue by ReneFroger** [syohex/emacs-helm-ag#296]
- Emacs version
_26.0.50_
- Operating system
_Xubuntu 17.04_
- Search command(ag, pt, ack etc) and version
_( helm-ag-base-command "ag --nocolor --nogroup --ignore-case")_
- Last value of `helm-ag--last-command`
> `("ag" "--nocolor" "--nogroup" "--ignore-case" "--ignore" "TAGS" "--ignore" "*.png" "--ignore" "file.js" "--ignore" "jquery.js" "--ignore" "jquery-2.1.0.min.js" "--ignore" "js/jquery-2.1.0.min.js" "--ignore" "jquery-3.0.0.min.js" "--ignore" "js/jquery-3.0.0.min.js" "--ignore" "jquery*.js" "--ignore" "bootstrap.js" "--ignore" "dataTables*.js" "--ignore" "dataTables.js" "--ignore" "data.js" "--ignore" "highcharts.js" "--ignore" "security.js" "--ignore" "**/*.min.js" "--ignore" "*/**.min.js" "--ignore" "**.min.js" "--ignore" "*.min.js" "--ignore" "js/jquery-3.0.0.min.js" "--ignore" "jquery-3.0.0.min.js" "--ignore" "js/jquery-2.1.0.min.js" "--ignore" "jquery-2.1.0.min.js" "--ignore" ".#*" "--ignore" "*.o" "--ignore" "*~" "--ignore" "*.bin" "--ignore" "*.lbin" "--ignore" "*.so" "--ignore" "*.a" "--ignore" "*.ln" "--ignore" "*.blg" "--ignore" "*.bbl" "--ignore" "*.elc" "--ignore" "*.lof" "--ignore" "*.glo" "--ignore" "*.idx" "--ignore" "*.lot" "--ignore" "*.fmt" "--ignore" "*.tfm" "--ignore" "*.class" "--ignore" "*.fas" "--ignore" "*.lib" "--ignore" "*.mem" "--ignore" "*.x86f" "--ignore" "*.sparcf" "--ignore" "*.dfsl" "--ignore" "*.pfsl" "--ignore" "*.d64fsl" "--ignore" "*.p64fsl" "--ignore" "*.lx64fsl" "--ignore" "*.lx32fsl" "--ignore" "*.dx64fsl" "--ignore" "*.dx32fsl" "--ignore" "*.fx64fsl" "--ignore" "*.fx32fsl" "--ignore" "*.sx64fsl" "--ignore" "*.sx32fsl" "--ignore" "*.wx64fsl" "--ignore" "*.wx32fsl" "--ignore" "*.fasl" "--ignore" "*.ufsl" "--ignore" "*.fsl" "--ignore" "*.dxl" "--ignore" "*.lo" "--ignore" "*.la" "--ignore" "*.gmo" "--ignore" "*.mo" "--ignore" "*.toc" "--ignore" "*.aux" "--ignore" "*.cp" "--ignore" "*.fn" "--ignore" "*.ky" "--ignore" "*.pg" "--ignore" "*.tp" "--ignore" "*.vr" "--ignore" "*.cps" "--ignore" "*.fns" "--ignore" "*.kys" "--ignore" "*.pgs" "--ignore" "*.tps" "--ignore" "*.vrs" "--ignore" "*.pyc" "--ignore" "*.pyo" "--ignore" "{arch}" "--ignore" "_darcs" "--ignore" "_MTN" "--ignore" ".bzr" "--ignore" ".hg" "--ignore" ".git" "--ignore" ".svn" "--ignore" ".src" "--ignore" "MCVS" "--ignore" "CVS" "--ignore" "RCS" "--ignore" "SCCS" "--ignore" "*templates/cache/" "--ignore" "templates/cache/" "--ignore" "templates/cache/" "--ignore" "*templates/cache/" "--ignore" ".idea/" "--ignore" ".ensime_cache/" "--ignore" ".eunit/" "--ignore" ".git/" "--ignore" ".hg/" "--ignore" ".fslckout/" "--ignore" "_FOSSIL_/" "--ignore" ".bzr/" "--ignore" "_darcs/" "--ignore" ".tox/" "--ignore" ".svn/" "--ignore" ".stack-work/" "--all-text" "hook")`

### Actual behavior
I have the following in my `.agignore`:

```
jquery*.js
jquery*.min.js
*.min.js
**.min.js
*/**.min.js
**/*.min.js
js/jquery-2.1.0.min.js
js/jquery-3.0.0.min.js
jquery-2.1.0.min.js
js/jquery-3.0.0.min.js
jquery*.js
jquery*.map
jquery.js
highcharts.js
dataTables*.js
bootstrap.js
bootstrap*.js
file.js

```
When I type a string, I noticed `helm-projectile-ag` also searches in `jquery-2.1.0.min.js` file. This file is in my `.agignore`.

### Expected behavior
I expected `helm-projectile-ag` to read from `.agignore`, and thus also ignoring the `jquery-2.1.0.min.js` file. I'm aware of the option `helm-ag-use-agignore`, but it's for projects. I would like to use my default `.agignore` in my home directory. Would that even be possible? 

### Expected behavior
I expected `helm-projectile-ag` to read from `.agignore`, and thus also ignoring the `jquery-2.1.0.min.js` file. I'm aware of the option `helm-ag-use-agignore`, but it's for projects.  I would like to use my default `.agignore` from my home directory, so also in projects. Would that even be possible?

**Comment by ReneFroger** [comment]
(setq helm-ag-command-option " -U" )

seems to solve this.

**Comment by enisozgen** [comment]
Just an info if you debug: There are 2 variables that changes the behavior ag. 

They are working as 
`helm-ag--last-command` = `helm-ag-base-command` + `helm-ag-command-option` + WhatYouSearch


### Defaults of those variables
(setq helm-ag-command-option nil)
(setq helm-ag-base-command "ag --nocolor --nogroup")

**Comment by rileyrg** [comment]
helm-ag-command-option is somewhat finicky/defined wrong. It wont allow things like --all-text. Complains :-

custom-variable-mark-to-save: Symbol’s value as variable is void: --all-text

Also complains of garbage if more than one option added here.
