### ISSUE TITLE
Feature request: Filter by file name

### ISSUE THREAD

**Issue by rcoedo** [syohex/emacs-helm-ag#297]
It would be great to be able to narrow the results even further using the filename from the results. Something like this:

1. Invoke `helm-ag`
2. Type in the pattern normally
3. Invoke a helm action, something like helm-ag-filter-file
4. Narrow previous results by the whole path, which would allow to filter extensions, directories or names

Thanks for this great package!

**Comment by mangosmoothie** [comment]
https://github.com/syohex/emacs-helm-ag#passing-command-line-options-and-pattern

Example below will search only files ending in md for the search pattern:

-Gmd$ search_pattern

**Comment by rcoedo** [comment]
That's exactly what I was looking for, thank you!
