### ISSUE TITLE
It would be better if there is a way to enable helm-ag on the current helm-ag result.

### ISSUE THREAD

**Issue by moyotar** [syohex/emacs-helm-ag#312]
- Emacs version: GNU Emacs 24.4.1
- Operating system: Debian GNU/Linux 8.8
- ag 0.26.0

For example, working in a big project, and I want to search something with `helm-projectile-ag`. After this, for more accurate, I often want to do `ag` again on the result of `helm-projectile-ag`. But now, there are only the below options.

![image](https://user-images.githubusercontent.com/22092607/34352968-7c18a9f6-ea60-11e7-9df8-c51de414ae72.png)

**Comment by CeleritasCelery** [comment]
Doesn't just typing another pattern separated by a space do the same thing?

**Comment by moyotar** [comment]
@CeleritasCelery Yes. For two patterns (named `A` and `B`)  separated by a space, the result is `A || B`, while I want to get `A && B`.

**Comment by CeleritasCelery** [comment]
That is not the case. The result contains both `A` and `B`. From the README. 

> When using ag or ack, helm-do-ag convert pattern from foo bar to "(?=.*" foo ".*)(?=.*" bar ".*)" which pattern matches line which contains both foo and bar.

**Comment by moyotar** [comment]
Oh! My fault. It works after I got `ag` up-to-date.
