### ISSUE TITLE
How to open a set of marked files?

### ISSUE THREAD

**Issue by vemv** [syohex/emacs-helm-ag#314]
Hello!

Say I mark N matches (files) with  C-SPC.

One has no way to open them all at once? Neither the `persistent action` or the `open file action` support acting upon more than one candidate.

Maybe more of issue in helm itself, but helm-ag does a pretty comprehensive wrapping so I'm not sure of where to look at.

Cheers - Victor

**Comment by Miciah** [comment]
This issue looks like a duplicate of issue #295.

**Comment by vemv** [comment]
Right!
