### ISSUE TITLE
ag/emacs regex interpretation

### ISSUE THREAD

**Issue by jeeger** [syohex/emacs-helm-ag#38]
I am trying to search for a string with parentheses in them. Because '(' is a special character in ag's regexes, I have to escape it. However, emacs regexes work the other way round, '\(' isn't a correct emacs regex, and thus, helm-ag--do-ag-propertize breaks when using ```(re-search-forward helm-input bound t)``` on line 269.

Since converting between emacs and pcre regexes is a huge task, I would propose adding ```--literal``` to the standard command line switches for ag.

**Comment by syohex** [comment]
@jeeger I implement function which converts from PCRE to Emacs Lisp regexp(but this is very simple).
Please check latest version.
