### ISSUE TITLE
add features found in helm-do-grep: helm buffer for folder selection, filename extension

### ISSUE THREAD

**Issue by mstorus** [syohex/emacs-helm-ag#43]
Hi, really enjoying `helm-do-ag`. I have a couple feature requests of things I find in `helm-do-grep` that I don't find in `helm-do-ag`:

1) When performing a recursive search, typing `C-u M-x helm-do-grep` launches a helm buffer to select the directory, whereas `C-u M-x helm-do-ag` brings up the default emacs directory selection. I would like to have `helm-do-ag` bring up a helm buffer to select the directory.

![emacs-helm-ag emacs-25 0 50 73x19-1-1](https://cloud.githubusercontent.com/assets/1182738/5102376/813a5aca-6f7e-11e4-97b2-c891418cfabf.jpg)

![emacs-helm-ag emacs-25 0 50 73x19-1](https://cloud.githubusercontent.com/assets/1182738/5102366/6428b40e-6f7e-11e4-9bfc-73799b9364aa.jpg)

2) `C-u M-x helm-do-grep` asks for a filename extension filter whereas `C-u M-x helm-do-ag` doesn't ask for a filename extension filter.
![emacs-helm-ag emacs-25 0 50 73x19-4](https://cloud.githubusercontent.com/assets/1182738/5102415/08af32a0-6f7f-11e4-9e72-6213dcd2660f.jpg)

**Comment by syohex** [comment]
Done

**Comment by AtomicNess123** [comment]
Is it possible to set a series of folders by default where always to search? Thanks.
