### ISSUE TITLE
Add ability to repeat search in the parent directory

### ISSUE THREAD

**Issue by vermiculus** [syohex/emacs-helm-ag#45]
With C/C++/etc., source and header files are often kept in separate directories. It would be phenomenal if, like `helm-find-file`, `C-l` was bound to repeat the search in the parent directory.

**Comment by syohex** [comment]
I have merged #48.

Please report me if you have any problems or suggestions.

**Comment by vermiculus** [comment]
Works fine with `helm-ag`, but does not appear to work with `helm-do-ag`

**Comment by syohex** [comment]
@vermiculus Sorry too late reply. I have merged this feature in `helm-do-ag` command at #49.
Please check latest version.

**Comment by vermiculus** [comment]
@syohex Works like a charm! Many thanks :smile:
