### ISSUE TITLE
Add pt support

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-helm-ag#46]
[Platinum Searcher](https://github.com/monochromegane/the_platinum_searcher) is a new text search tool similar to `ag`, but is a bit faster. Reasons to support it:

- It has a binary distribution for Windows. A single binary file, `pt.exe`. Making `ag` works on Windows [is more complicated](https://github.com/ggreer/the_silver_searcher/wiki/Windows). Currently, my only viable option on Windows is `grep`.

- Its syntax is similar to `ag`. In fact, I replace [helm-ag--construct-do-ag-command](https://github.com/syohex/emacs-helm-ag/blob/master/helm-ag.el#L275) with plain list of `pt` arguments and it works fine. Note that on Windows, instead of starting with `--` for each option, it starts with a slash `/`. So, you should have `(window-system)` check to prepare correct option syntax.

An example of plain `pt` command:

```sh
pt --nogroup --nocolor <pattern> <directory>
```

On Windows:

```sh
pt /nogroup /nocolor <pattern> <directory>
```
You may hesitate because this package is named `helm-ag` :) . I think it is fine, given that `helm-do-grep` also has extended support for `ack`, so `helm-ag` provides extended support for `pt` is only beneficial.

**Comment by syohex** [comment]
`pt` has several issues when it is used from Emacs.
- checking stdin type
- return value

I should fix them first.

**Comment by tuhdo** [comment]
Thank you for supporting it.

**Comment by syohex** [comment]
My PR are merged. So `helm-ag` also works with `pt`.

I confirmed `helm-ag` works with `pt` by following configuration.
```lisp
(setq helm-ag-base-command "pt --nocolor --nogroup")
```

**Comment by tuhdo** [comment]
Great. Thanks.

**Comment by ralesi** [comment]
Can you walk my through troubleshooting this?  I cannot get any update to the helm buffer when trying this solution.  

Currently running on Windows.  Pt works fine from the command line.

**Comment by syohex** [comment]
Do you use latest `pt` ?

**Comment by ralesi** [comment]
Yes, also runs fine with running the line created from `helm-ag-base-command` within eshell. I can't see any output from `helm-do-ag` either

**Comment by syohex** [comment]
@ralesi Ah, sorry, do you build pt from source code such as `go get` ? 

I fixed issue for running pt in Emacs at https://github.com/monochromegane/the_platinum_searcher/pull/71 and https://github.com/monochromegane/the_platinum_searcher/pull/72. The binary which contains those fixes is not released yet. So we have to built it from source code now.

**Comment by syohex** [comment]
@ralesi helm-ag has issue for Windows environemnt.

**Comment by syohex** [comment]
@ralesi Please upgrade helm-ag version and pt version(1.7.7 or installing from source code). I fixed both helm-ag Windows issue and pt Windows issue. I confirmed both `helm-ag` and `helm-do-ag` works well on Windows.
