### ISSUE TITLE
Easier way to specify command line options to ag

### ISSUE THREAD

**Issue by mstorus** [syohex/emacs-helm-ag#51]
There are several `ag` command line options that I frequently toggle on or off. For example:

```
-G, --file-search-regex PATTERN:
     Only search filenames matching PATTERN.
-s --case-sensitive:
     Match case sensitively.
-w --word-regexp:
     Only match whole words.
```

Currently the easiest way I've found to set these is to do `M-x customize-option helm-ag-command-option`, edit the customization buffer, save, return to other buffer, etc.

But that is very tedious to set and unset these variables all the time.

Could there be an easier way? For me, the best would be for `helm-do-ag` to prompt for command options every time. And I could just press Return to accept the last used setting.

**Comment by syohex** [comment]
Now there are no way. I'm fixing this issue at #52.
Please wait.

**Comment by syohex** [comment]
#### helm-ag

![helm-ag-option1](https://cloud.githubusercontent.com/assets/554281/5779646/df3bb366-9de7-11e4-80c7-a181175437fc.gif)

**Comment by syohex** [comment]
#### WIP helm-do-ag

```lisp
(setq helm-ag-always-set-extra-option t)
```

If `helm-ag-always-set-extra-option` is non-nil, you can specify extra options of `helm-do-ag`
everytime.

**Comment by syohex** [comment]
@mstorus Would you check latest version ?

**Comment by mstorus** [comment]
hi @syohex 

The interaction is great!

I think I noticed a bug though:
First I did `M-x customize-option helm-ag-always-set-extra-option` and toggled it on. Then I performed a `helm-do-ag` and specified `Extra options: -w`. As expected, `ag` searched with the `-w` flag, only showing whole word matches.
But then, I performed another `helm-do-ag`, and set `Extra options :` (I deleted the `-w`), and `ag` was still only matching whole words. So it seems clearing the `Extra options` didn't work.

**Comment by syohex** [comment]
> But then, I performed another helm-do-ag, and set Extra options : (I deleted the -w), and ag was still only matching whole words. So it seems clearing the Extra options didn't work.

Thanks for good catch. I've fixed at #53. Please check latest version.

**Comment by mstorus** [comment]
Great, thank you! It works as expected now

**Comment by syohex** [comment]
You are welcome.

**Comment by tddsg** [comment]
Hi, this is a really good customization for `helm-do-ag`. I wonder if this toggle on/off of  `helm-ag-always-set-extra-option` can be done intuitively in the helm display result? This will be even more convenient! Thanks!
