### ISSUE TITLE
can't select directory unless I use C-u

### ISSUE THREAD

**Issue by mstorus** [syohex/emacs-helm-ag#56]
Starting with https://github.com/syohex/emacs-helm-ag/commit/1529c4272ead72320ca230a241889981c77ff5eb I'm not able to specify a search directory anymore when performing `M-x helm-do-ag`. It does ask for a directory if I do `C-u M-x helm-do-ag` though

In my opinion it should still ask for a directory every time (even without `C-u`). Perhaps it could default to the git root, or the last used directory. Asking for a directory each time is useful for large projects, and also more intuitive for new users.

**Comment by syohex** [comment]
I'll implement the feature like this at #55.
I think it is better that `helm-do-ag` has same interface as `helm-do-grep`.

**Comment by syohex** [comment]
Done
