### ISSUE TITLE
`helm-do-ag` not setting base directory correctly?

### ISSUE THREAD

**Issue by mjhoy** [syohex/emacs-helm-ag#57]
steps:
run emacs -Q and eval:
```
(package-initialize)
(require 'helm)
(require 'helm-ag)
```
Assume I have the following files:
```
~/helm-test/a/one.txt
~/helm-test/b/two.txt (contains text "hello")
```

Using `helm-ag`, I can:
1. visit `~/helm-test/a/one.txt`
2. `C-u M-x helm-ag RET ~/helm-test/ RET hello`
3. Finds `b/two.txt` and I can jump to it.

However, using `helm-do-ag`, this doesn't work.
1. visit `~/helm-test/a/one.txt`
2. `C-u M-x helm-do-ag RET ~/helm-test RET RET hello`
3. It correctly finds the file, but when I go to jump to it, it takes me to the non-existent file at `~/b/two.txt`, **not** `~/helm-test/b/two.txt`.

This problem means that the [helm search provided from `helm-projectile.el`][1] never works for me. If I swap `helm-do-ag` with `helm-ag` it works fine.

[1]:https://github.com/bbatsov/projectile/blob/master/helm-projectile.el#L727-L744

**Comment by mjhoy** [comment]
also, i'm on OSX 10.9 and use:

```
$ emacs --version
GNU Emacs 24.4.1  [..]

$ ag --version
ag version 0.28.0

  helm               20150122.546 installed             Helm is an Emacs incremental and narrowing framework
  helm-ag            20150122.634 installed             the silver searcher with helm interface
```

**Comment by mjhoy** [comment]
Another weird thing: if I run a `helm-do-ag` search as above, within `~/helm-test`, and then later run a separate search in say `~/.emacs.d`, instead of taking me to a file that matches a search, say `~/.emacs.d/site-lisp/helm-mu/helm-mu.el`, it will instead take me to: `~/helm-test/a/site-lisp/helm-mu/helm-mu.el`. So some kind of state is persisting and not updated between searches?

**Comment by duerrp** [comment]
I am having the same problem here...

**Comment by syohex** [comment]
Sorry I fixed issue that helm-projectile-ag does not work at #58.
Please check latest version.

> However, using helm-do-ag, this doesn't work.
> 1. visit ~/helm-test/a/one.txt
> 2. C-u M-x helm-do-ag RET ~/helm-test RET RET hello
> 3. It correctly finds the file, but when I go to jump to it, it takes me to the non-existent file at ~/b/two.txt, not ~/helm-test/b/two.txt.

I don't understand this well.

**Comment by syohex** [comment]
> However, using helm-do-ag, this doesn't work.
> 1. visit ~/helm-test/a/one.txt
> 2. C-u M-x helm-do-ag RET ~/helm-test RET RET hello
> 3. It correctly finds the file, but when I go to jump to it, it takes me to the non-existent file at ~/b/two.txt, not ~/helm-test/b/two.txt.

I cannot reproduce this behavior. My screencast is below.
Would you tell me what I was wrong ?


![helm-ag](https://cloud.githubusercontent.com/assets/554281/5894620/a10bfa16-a54d-11e4-862a-35b96a484a31.gif)

**Comment by mjhoy** [comment]
@syohex I'm having a little trouble reproducing it too, exactly as I have it! Strange. However, try this:

After searching in `~/helm-test` for a file, following immediately with a search from `~/helm-test/b`.

See my screencast. After first searching in `~/helm-test` I then make the same search from `~/helm-test/b`, and instead of taking me to the match in `~/helm-test/b/two.txt` it takes me to `~/two.txt`.

https://dl.dropboxusercontent.com/u/2239902/helm-ag.mp4

**Comment by syohex** [comment]
Thanks for information. I can reproduce.

**Comment by syohex** [comment]
@mjhoy I fixed at #60. Please check latest version.

**Comment by mjhoy** [comment]
@syohex working now for me. thanks!

**Comment by duerrp** [comment]
Excellent! Thanks for the quick fix...
