### ISSUE TITLE
Truncate long lines

### ISSUE THREAD

**Issue by k1-hedayati** [syohex/emacs-helm-ag#63]
When there is a match in a minified js or css file it ruins helm buffer.
`ag` itself has an option for this `--print-long-lines   Print matches on very long lines (Default: >2k characters)` but it doesn't accept any parameter.

**Comment by syohex** [comment]
You can use `helm-truncate-lines` for truncating long lines.

```lisp
(setq helm-truncate-lines t)
```

**Comment by k1-hedayati** [comment]
Nice! Thank you
