### ISSUE TITLE
C-j (helm-ag-persistent-action) not working anymore

### ISSUE THREAD

**Issue by duerrp** [syohex/emacs-helm-ag#64]
First, let me thank you for this great package. Love it.

Unfortunately, C-j stopped working with the last update. Any insight what the problem could be?
Thanks for your help!

**Comment by syohex** [comment]
Thanks for information. It's bug. I'll fix soon.

**Comment by syohex** [comment]
@duerrp  I have fixed at #65. Please check latest version.

**Comment by duerrp** [comment]
Perfect, I can confirm it works again. Thank you very much for the quick fix!
