### ISSUE TITLE
Strange characters

### ISSUE THREAD

**Issue by arichiardi** [syohex/emacs-helm-ag#67]
I get some strange behaviour on helm-do-ag. A picture is worth one thousand words.

![selection_001](https://cloud.githubusercontent.com/assets/1724788/6194017/a10d658c-b3c0-11e4-8472-1b9e1897929a.png)

**Comment by syohex** [comment]
Do you change `helm-ag-base-command` variable ?
And is there `--nocolor` option in it ?

**Comment by arichiardi** [comment]
You are right, I had delede --nocolor, now is fine, thanks!
