### ISSUE TITLE
How make Helm-ag editable and saving?

### ISSUE THREAD

**Issue by ReneFroger** [syohex/emacs-helm-ag#68]
Thanks for sharing this awesome addition to Helm. I really appreciate it. 

However, I have a question. In Vim, you type `:Ag example`. Then you see the lines which contains the word 'example' in Quickfix window. Then with Quickfix Reflector, you change the values of each line, and save it back to multiple files. The [Emacs-wgrep](https://github.com/mhayashi1120/Emacs-wgrep) seems using the same technique as Quickfix Reflector. 
An example in Vim:
![agcontent](https://cloud.githubusercontent.com/assets/5211845/6201457/bba1d00a-b4aa-11e4-9d81-807189bc7bea.gif)

 I haven't figured out how to the same with Helm Ag. Could this even be possible?

**Comment by syohex** [comment]
Sorry, there is no way for this feature.
(This is duplicated #2.)

**Comment by ReneFroger** [comment]
Thanks for your reply. Could you explain in detail why this is impossible?

 For example, [Helm Swoop from Shingo Fukuyama](https://github.com/ShingoFukuyama/helm-swoop) enables you to edit the filtered output from multiple buffers in Helm buffer, and save it across multiple buffers. So the Helm platform and interface allows this kind of operation, it seems. 

Thanks in advance for your reply.

**Comment by syohex** [comment]
> Could you explain in detail why this is impossible?

It is possible, but I have not implemented this feature.

**Comment by ReneFroger** [comment]
Is there any chance that you could implement this feature, by the way?

 From what I hear, not only me would want this feature into Helm Ag.

**Comment by tuhdo** [comment]
@syohex is it possible to quickly reuse implementation of the function `helm-grep-save-results-1` from `helm-do-grep`. It already implemented `helm-grep-mode` that turns a buffer with matches similar to the output of `helm-do-grep` (which is basically the same as `helm-do-ag`) to a Grep buffer that you can use Wgrep on it.

**Comment by syohex** [comment]
I'm implementing this feature at #69 now. Please wait.

**Comment by syohex** [comment]
I have merged #69.

Please check latest version. You can switch to edit mode by `C-c C-e`.
You edit something.

And you can save by `C-c C-c`(abort by `C-c C-k`)

**Comment by tuhdo** [comment]
Awesome. Thanks for adding this. I will try it soon.

**Comment by syl20bnr** [comment]
:+1:

**Comment by ReneFroger** [comment]
Just tested out. Awesome, works like a charm. 

Thanks for your tremendous job, syohex!

**Comment by tninja** [comment]
This could be really useful. Thank you!
