### ISSUE TITLE
Provide a way to save helm-ag results in a buffer

### ISSUE THREAD

**Issue by tmccombs** [syohex/emacs-helm-ag#72]
This would work similar to the C-x C-s binding for helm-do-grep.

**Comment by syohex** [comment]
Would you tell me use case of this feature?
(I suppose it is enough to use `C-u M-x helm-resume`.)

**Comment by tmccombs** [comment]
One use case where helm-resume wouldn't work is if you search for one pattern, and then want to search for another pattern while keeping the results from the first search.

**Comment by syohex** [comment]
I have implemented saving buffer feature at #76.
Please check latest version.

**Comment by jonEbird** [comment]
I'm new to using helm-ag and was also looking for this feature. It works but there is a bug when calling `helm-do-ag` while passing the parent directory for `basedir` in that the recorded path has an extra directory in the path.  

I'm actually invoking this function via `projectile` (C-c p s s ) but I can reproduce it manually as well by passing the parent directory of my current `buffer-file-name` like so:
    
    (helm-do-ag
     (file-name-directory (directory-file-name (file-name-directory buffer-file-name))))

If I do not save the results, hitting RET takes me to the correct spot but with the saved results, a `c-o` includes an extra directory and not the correct file.
