### ISSUE TITLE
Show pattern match files relative to the search path

### ISSUE THREAD

**Issue by mstorus** [syohex/emacs-helm-ag#82]
Hi,

I think it would be nice to have the files matched through `helm-do-ag` to have their paths relative to the search path provided.

For example, here I have `emacs-helm-ag/test/test-util.el` open, but I specify the search to be up one directory (in `emacs-helm-ag/`)

![emacs-helm-ag emacs-25 0 50 73x19-7](https://cloud.githubusercontent.com/assets/1182738/6762597/ca998180-cf20-11e4-9179-170c18611516.png)

When the results come up, the paths are relative to the currently open file, as opposed to the search path specified in the screenshot above

![emacs-helm-ag emacs-25 0 50 73x19](https://cloud.githubusercontent.com/assets/1182738/6762591/ae85a53c-cf20-11e4-91dc-4061102d02f1.png)

I think it would be nice to show `README.md` instead of `../README.md`

**Comment by syohex** [comment]
@mstorus I have implemented this feature at #85.
Please check latest version.
