### ISSUE TITLE
Persistent action doesn't work after going up a directory by 'C-l'

### ISSUE THREAD

**Issue by alpha22jp** [syohex/emacs-helm-ag#86]
Persistent action after going up a directory by 'C-l' invokes an error "Wrong type argument". Please take a look at the screenshot below.

![output](https://cloud.githubusercontent.com/assets/6090562/6780528/6fb3918a-d1a9-11e4-9032-0925be87d7ca.gif)

**Comment by syohex** [comment]
Thanks for reporting issue.
I fixed at this issue at #87. Please check latest version.

**Comment by alpha22jp** [comment]
Works fine :smile: Thanks.
