### ISSUE TITLE
AG replacement for helm-find-files-grep

### ISSUE THREAD

**Issue by killdash9** [syohex/emacs-helm-ag#88]
This is the helm-projectile action when C-s is pressed on a project in the projects list (C-c p p).  It can be replaced trivially with the an ag version with the following code:

    (defun helm-find-files-ag (candidate)
      "Default action to grep files from `helm-find-files'.  Replaces helm-find-files-grep."
      (let ((default-directory candidate))
        (helm-projectile-ag)))
    (defalias 'helm-find-files-grep 'helm-find-files-ag)

**Comment by syohex** [comment]
What's your issue ?

**Comment by killdash9** [comment]
I guess this is more of a feature request, to substitute ag for grep more broadly in helm-projectile.
