### ISSUE TITLE
Does it support .agignore

### ISSUE THREAD

**Issue by andyque** [syohex/emacs-helm-ag#98]
I know ag could use .agignore to ignore some pattern specified in the .agignore file.

I can use it in Projectile-ag, but helm-ag seems doesn't support it?

Am I miss something here?

thanks.

**Comment by syohex** [comment]
It works if `.agignore` in home directory `~/.agignore`.

[projectile](https://github.com/bbatsov/projectile/) and [ag.el](https://github.com/Wilfred/ag.el) don't care `.agignore`, so I suppose `helm-ag` works same as them.

**Comment by andyque** [comment]
Thanks, @syohex 

Could I provide a project wide `.agignore` file? Like in a git repository

**Comment by syohex** [comment]
`ag` uses only .agignore file where is under searched directories.

If you can search from project root then `ag` command uses .agignore file where is at
root of project. `helm-ag-project-root`, `helm-do-ag-project-root`, `projectile-ag` searches
from project root.

**Comment by syohex** [comment]
I added flag for using `.agignore file`. It is `helm-ag-use-agignore `. If you use `.agignore` file, please set following configuration in your configuration files.

```lisp
(setq helm-ag-use-agignore t)
```
